### ISSUE TITLE
ld segfaults on helloworld.c

### ISSUE THREAD

**Issue by lesderid** [darlinghq/darling#363] opened 2017-12-05 17:47 UTC
`ld` from Apple's Command Line Tools segfaults on simple applications linking only to libSystem.

This was tested with both Command Line Tools for Xcode 7 (10.10) and for Xcode 9 (10.13).

Isn't this a regression? I vaguely remember this working before.

Tested on https://github.com/darlinghq/darling/commit/0a4ede7d082c35ea8ddeb169da77ae48ab01f1fb with up-to-date submodules (Arch Linux, kernel 4.13.12-1-ARCH):

```
Darling [~/darling]$ cat helloworld.c                                            
void main() { puts("Hello world"); }

Darling [~/darling]$ clang -c helloworld.c                                       
helloworld.c:1:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main() { puts("Hello world"); }
^
helloworld.c:1:1: note: change return type to 'int'
void main() { puts("Hello world"); }
^~~~
int
helloworld.c:1:15: warning: implicit declaration of function 'puts' is invalid in C99 [-Wimplicit-function-declaration]
void main() { puts("Hello world"); }
              ^
2 warnings generated.

Darling [~/darling]$ ld -dynamic -arch x86_64 -o helloworld helloworld.o -lSystem
Segmentation fault: 11 (core dumped)
```

**Comment by lesderid** [comment] 2017-12-05 17:54
This might be related to https://github.com/darlinghq/darling/issues/361?

**Comment by LubosD** [comment] 2018-07-18 21:17
Closing as a duplicate of #361

**Closed by LubosD** 2018-07-18 21:17 UTC
Labels: Bug
