### ISSUE TITLE
wsl lkm /lib/modules/  not found

### ISSUE THREAD

**Issue by DeusSeos** [darlinghq/darling#1097] opened 2022-01-28 17:32 UTC
**Expected Result**
lkm to build

**Actual Result**
```
Built target lkm_generate
Built target rtsig
Built target rtsig_h
Building the Linux kernel module
make[4]: Entering directory '/home/dc/darling/src/external/lkm'
Running kernel version is 5.10.74.3-microsoft-standard-WSL2+
rm -f darling-mach.mod.o
make -C /lib/modules/5.10.74.3-microsoft-standard-WSL2+/build M=/home/dc/darling/src/external/lkm modules
make[5]: Entering directory '/home/dc/darling/src/external/lkm'
make[5]: *** /lib/modules/5.10.74.3-microsoft-standard-WSL2+/build: Not a directory.  Stop.
make[5]: Leaving directory '/home/dc/darling/src/external/lkm'
make[4]: *** [Makefile:618: default] Error 2
make[4]: Leaving directory '/home/dc/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:61672: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:61679: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:20158: lkm] Error 2
```

**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
```

```

**System Information**
What system are you using?

| Ubuntu | Ubuntu 20.04.3 LTS |
| --- | --- |
| Darling-wsl-kernel | 5.10.74 |
| Darling | 597325bc7 |

**Comment by facekapow** [comment] 2022-01-28 17:35
Duplicate of #1091

**Closed by facekapow** 2022-01-28 17:35 UTC
