### ISSUE TITLE
Build Error on Manjaro error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0

### ISSUE THREAD

**Issue by cgjames907** [darlinghq/darling#894] opened 2020-11-20 23:45 UTC
**Build Log**
```
/home/ibanez/Src/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:34:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT
     ^
In file included from /home/ibanez/Src/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:50:
/home/ibanez/Src/darling/src/dyld/src/ImageLoader.h:46:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
In file included from /home/ibanez/Src/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:50:
In file included from /home/ibanez/Src/darling/src/dyld/src/ImageLoader.h:53:
In file included from /home/ibanez/Src/darling/src/dyld/dyld3/shared-cache/DyldSharedCache.h:41:
In file included from /home/ibanez/Src/darling/src/dyld/dyld3/MachOAnalyzer.h:28:
In file included from /home/ibanez/Src/darling/src/dyld/dyld3/MachOLoaded.h:29:
/home/ibanez/Src/darling/src/dyld/dyld3/Array.h:33:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
/home/ibanez/Src/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:85:41: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if __IPHONE_OS_VERSION_MIN_REQUIRED || TARGET_OS_DRIVERKIT
                                        ^
/home/ibanez/Src/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:1381:5: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_DRIVERKIT
    ^
/home/ibanez/Src/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:1488:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT
     ^
6 errors generated.
make[2]: *** [src/dyld/CMakeFiles/system_dyld_obj.dir/build.make:82: src/dyld/CMakeFiles/system_dyld_obj.dir/src/dyldAPIsInLibSystem.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:16608: src/dyld/CMakeFiles/system_dyld_obj.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**System Information**
Linux MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux

| Software | Version |
| --- | --- |
| Clang | clang version 11.0.0 |
| CMake | cmake version 3.18.4 |
| Kernel | Linux Kernel 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux |
| Darling commit hash | 1d3b09970856d58d12867f4ee5b9b1bf84cd05c2 |

**Comment by HinTak** [comment] 2020-11-21 02:21
Same issue reported earlier https://github.com/darlinghq/darling/issues/892

**Comment by rdrpenguin04** [comment] 2020-11-26 17:36
Also duplicate of #856

**Comment by facekapow** [comment] 2020-11-27 03:02
Closing in favor of #856

**Closed by facekapow** 2020-11-27 03:02 UTC
