### ISSUE TITLE
Darling guide doesn't mention libstdc++ and its version

### ISSUE THREAD

**Issue by nuschpl** [darlinghq/darling#1338] opened 2023-03-16 18:43 UTC
I'm trying to follow build guide of darling on ubuntu 22.04. 
Cmake fails early with:
` /usr/bin/ld: cannot find -lstdc++: No such file or directory`
So I assume I need to install one of the packages  named libstdc++-**X**-dev. Altough there are plenty versions of this lib available on my system- half installed and half not installed I don't know which one I should point. Kindly please advise which one I should choose so I can debug further if it's missing or cmake has problem catching it. 

> $ LANG="en" apt-cache policy libstdc++-{5..12}-dev
> libstdc++-5-dev:
>   Installed: 5.5.0-12ubuntu1
>   Candidate: 5.5.0-12ubuntu1
>   Version table:
>  *** 5.5.0-12ubuntu1 100
>         100 /var/lib/dpkg/status
> libstdc++-6-dev:
>   Installed: 6.5.0-2ubuntu1~18.04
>   Candidate: 6.5.0-2ubuntu1~18.04
>   Version table:
>  *** 6.5.0-2ubuntu1~18.04 100
>         100 /var/lib/dpkg/status
> libstdc++-7-dev:
>   Installed: 7.5.0-6ubuntu2
>   Candidate: 7.5.0-6ubuntu2
>   Version table:
>  *** 7.5.0-6ubuntu2 100
>         100 /var/lib/dpkg/status
> libstdc++-9-dev:
>   Installed: 9.5.0-1ubuntu1~22.04
>   Candidate: 9.5.0-1ubuntu1~22.04
>   Version table:
>  *** 9.5.0-1ubuntu1~22.04 500
>         500 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
>         100 /var/lib/dpkg/status
>      9.4.0-5ubuntu1 500
>         500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
> libstdc++-10-dev:
>   Installed: (none)
>   Candidate: 10.4.0-4ubuntu1~22.04
>   Version table:
>      10.4.0-4ubuntu1~22.04 500
>         500 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
>      10.3.0-15ubuntu1 500
>         500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
> libstdc++-11-dev:
>   Installed: 11.3.0-1ubuntu1~22.04
>   Candidate: 11.3.0-1ubuntu1~22.04
>   Version table:
>  *** 11.3.0-1ubuntu1~22.04 500
>         500 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
>         500 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages
>         100 /var/lib/dpkg/status
>      11.2.0-19ubuntu1 500
>         500 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages
> libstdc++-12-dev:
>   Installed: (none)
>   Candidate: 12.1.0-2ubuntu1~22.04
>   Version table:
>      12.1.0-2ubuntu1~22.04 500
>         500 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages
>      12-20220319-1ubuntu1 500
>         500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
> N: Unable to locate package libstdc++-8-dev
> N: Couldn't find any package by regex 'libstdc++-8-dev'

**Comment by Anvith00** [comment] 2023-03-17 20:03
Greetings @nuschpl . I tried building this against Ubuntu 22.04 inside a virtual machine, however, I was unable to reproduce your issue. However, I had these two versions of libstdc++ installed: `libstdc++-11-dev` and `libstdc++6`.

**Comment by nuschpl** [comment] 2023-03-17 21:36
So which of those two versions is linked against darling? Are there
specific expectations from darling regarding libstdc++ functionality what
would determine minimum version?
Regards

pt., 17 mar 2023, 21:04 użytkownik TauntArrow69099 ***@***.***>
napisał:

**Comment by facekapow** [comment] 2023-10-16 02:34
Closing this since our docs now list `libstdc++-12-dev` as a dependency on Ubuntu 22.04.

**Closed by facekapow** 2023-10-16 02:34 UTC
