### ISSUE TITLE
fatal: remote error: upload-pack: not our ref 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4

### ISSUE THREAD

**Issue by Yingsheng-eroad** [darlinghq/darling#704] opened 2020-03-09 01:50 UTC
I got an error when trying to git clone the repo.
`fatal: remote error: upload-pack: not our ref 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4
Fetched in submodule path 'src/external/top', but it did not contain 8bc7d87e088fdcd53c47ebf5460acc004f6b4fc4. Direct fetching of that commit failed.`

**Comment by facekapow** [comment] 2020-03-09 02:34
I've submitted a PR (#703) that should fix this once merged.

As a temporary workaround, you could try doing this:

```
git clone https://github.com/darlinghq/darling
cd darling
git submodule init
git remote add facekapow https://github.com/facekapow/darling.git
git fetch facekapow
git checkout -b fix-top-commit facekapow/fix-top-commit
git submodule update
```

You have to do `git submodule init` before checking out my branch because Darling uses relative submodule URLs, and you want the submodules to point to `darlinghq`'s repositories, not mine.

**Closed** 2020-03-09 20:18 UTC

**Comment by cheryl-catalog** [comment] 2022-09-01 20:27
I am seeing an issue today @facekapow
Thanks in advance.

**Comment by brunocascio** [comment] 2022-09-08 15:44
I'm facing this issue too. I'm currently running argocd 2.4.11 version

**Comment by cheryl-catalog** [comment] 2022-09-08 16:04
The issue I was seeing was caused by a developer creating a branch in a submodule and committing the change from the parent. In GitHub, the developer did not have permission to create a branch in the submodule. The changes were reverted, and everything is fine now.

**Comment by RawanIb** [comment] 2024-04-24 11:02
How you fixed that and reveret committed changes?

**Comment by joshhansen** [comment] 2024-11-05 00:19
I had this on `git clone`. The remote repo had been created a while back, so I suspect there was probably an old bug in repository initialization. I had only one commit of history, so I just deleted the .git folder and recommitted all the files. Then the clone worked. Obviously not the solution for everyone but maybe that provides a hint.
