### ISSUE TITLE
Clang 7 segfaults building darling

### ISSUE THREAD

**Issue by Dekken** [darlinghq/darling#412] opened 2018-08-06 10:59 UTC
Debian 9 / host gcc 6.3

```
clang-7: error: unable to execute command: Segmentation fault
clang-7: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by bugaevc** [comment] 2018-08-06 11:05
Looks like it's our build of `ld64` that segfaults, not `clang`. What's it linking exactly?

**Comment by Dekken** [comment] 2018-08-06 11:26
```
[ 12%] Built target platform_static32
[ 12%] Building C object src/external/libplatform/CMakeFiles/platform_obj.dir/src/string/generic/strncmp.o
[ 12%] Building C object src/external/libplatform/CMakeFiles/platform_obj.dir/src/string/generic/bzero.o
Scanning dependencies of target compiler_rt_firstpass
[ 12%] Building C object src/external/perl/5.18/CMakeFiles/perlcore.dir/doop.o
[ 12%] Linking C shared library libcompiler_rt_firstpass.dylib
clang-7: warning: argument unused during compilation: '-nostdinc' [-Wunused-command-line-argument]
clang-7: error: unable to execute command: Segmentation fault
clang-7: error: linker command failed due to signal (use -v to see invocation)
src/external/compiler-rt/lib/builtins/CMakeFiles/compiler_rt_firstpass.dir/build.make:632: recipe for target 'src/external/compiler-rt/lib/builtins/libcompiler_rt_firstpass.dylib' failed
make[2]: *** [src/external/compiler-rt/lib/builtins/libcompiler_rt_firstpass.dylib] Error 254
CMakeFiles/Makefile2:16003: recipe for target 'src/external/compiler-rt/lib/builtins/CMakeFiles/compiler_rt_firstpass.dir/all' failed
make[1]: *** [src/external/compiler-rt/lib/builtins/CMakeFiles/compiler_rt_firstpass.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Dekken** [comment] 2018-08-06 12:04
dropping to apt version of clang/llvm-6 has resolved this

**Comment by ahyattdev** [comment] 2018-11-24 03:39
I am using `clang version 7.0.0-3` on Ubuntu 18.10 and have not experienced this issue, so I'm closing this for now. We can reopen if we can reproduce this.

**Closed by ahyattdev** 2018-11-24 03:39 UTC
Labels: Build
