### ISSUE TITLE
xcode-select cannot install 

### ISSUE THREAD

**Issue by android-leha** [darlinghq/darling#1030] opened 2021-09-10 09:37 UTC
Hey

I'm running `xcode-select --install`, but it is failing with following exception:

```
Traceback (most recent call last):
  File "/usr/libexec/darling/clt_install.py", line 36, in <module>
    packagesResp = urllib2.urlopen("https://swdistcache.darlinghq.org/api/v1/products/by-tag?tag=DTCommandLineTools")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

Looks like `https://swdistcache.darlinghq.org/api/v1/products/by-tag?tag=DTCommandLineTools` isn't working.

**Comment by LubosD** [comment] 2021-09-10 09:52
Duplicate of #1006

**Closed by LubosD** 2021-09-10 09:52 UTC
