### ISSUE TITLE
can't build LKM on kernel 5.7, 5.8 or 5.9

### ISSUE THREAD

**Issue by ringtailedfox** [darlinghq/darling#887] opened 2020-10-23 02:35 UTC
**Build Log**
What is the build error?
```
[user@localhost build (master)]$ make lkm
Built target migcom
Built target migexe
Generating osfmk/mach/upl_user.c, osfmk/mach/upl.h, osfmk/mach/upl_server.c, osfmk/mach/upl_server.h, osfmk/mach/uplXtraceMig.c
Generating osfmk/mach/host_notify_reply_user.c, osfmk/mach/host_notify_reply.h, osfmk/mach/host_notify_reply_server.c, osfmk/mach/host_notify_reply_server.h, osfmk/mach/host_notify_replyXtraceMig.c
Generating osfmk/mach/vm32_map_user.c, osfmk/mach/vm32_map.h, osfmk/mach/vm32_map_server.c, osfmk/mach/vm32_map_server.h, osfmk/mach/vm32_mapXtraceMig.c
Generating osfmk/mach/mach_notify_user.c, osfmk/mach/mach_notify.h, osfmk/mach/mach_notify_server.c, osfmk/mach/mach_notify_server.h, osfmk/mach/mach_notifyXtraceMig.c
Generating osfmk/mach/mach_voucher_attr_control_user.c, osfmk/mach/mach_voucher_attr_control.h, osfmk/mach/mach_voucher_attr_control_server.c, osfmk/mach/mach_voucher_attr_control_server.h, osfmk/mach/mach_voucher_attr_controlXtraceMig.c
Generating osfmk/mach/memory_object_control_user.c, osfmk/mach/memory_object_control.h, osfmk/mach/memory_object_control_server.c, osfmk/mach/memory_object_control_server.h, osfmk/mach/memory_object_controlXtraceMig.c
Generating osfmk/mach/memory_object_user.c, osfmk/mach/memory_object.h, osfmk/mach/memory_object_server.c, osfmk/mach/memory_object_server.h, osfmk/mach/memory_objectXtraceMig.c
Generating osfmk/mach/memory_object_default_user.c, osfmk/mach/memory_object_default.h, osfmk/mach/memory_object_default_server.c, osfmk/mach/memory_object_default_server.h, osfmk/mach/memory_object_defaultXtraceMig.c
Generating osfmk/mach/mach_voucher_user.c, osfmk/mach/mach_voucher.h, osfmk/mach/mach_voucher_server.c, osfmk/mach/mach_voucher_server.h, osfmk/mach/mach_voucherXtraceMig.c
Generating osfmk/mach/vm_map_user.c, osfmk/mach/vm_map.h, osfmk/mach/vm_map_server.c, osfmk/mach/vm_map_server.h, osfmk/mach/vm_mapXtraceMig.c
Generating osfmk/mach/resource_notify_user.c, osfmk/mach/resource_notify.h, osfmk/mach/resource_notify_server.c, osfmk/mach/resource_notify_server.h, osfmk/mach/resource_notifyXtraceMig.c
Generating osfmk/mach/exc_user.c, osfmk/mach/exc.h, osfmk/mach/exc_server.c, osfmk/mach/exc_server.h, osfmk/mach/excXtraceMig.c
Generating osfmk/mach/mach_exc_user.c, osfmk/mach/mach_exc.h, osfmk/mach/mach_exc_server.c, osfmk/mach/mach_exc_server.h, osfmk/mach/mach_excXtraceMig.c
Generating osfmk/mach/notify_user.c, osfmk/mach/notify.h, osfmk/mach/notify_server.c, osfmk/mach/notify_server.h, osfmk/mach/notifyXtraceMig.c
Generating osfmk/mach/task_user.c, osfmk/mach/task.h, osfmk/mach/task_server.c, osfmk/mach/task_server.h, osfmk/mach/taskXtraceMig.c
Generating osfmk/mach/clock_user.c, osfmk/mach/clock.h, osfmk/mach/clock_server.c, osfmk/mach/clock_server.h, osfmk/mach/clockXtraceMig.c
Generating osfmk/mach/clock_priv_user.c, osfmk/mach/clock_priv.h, osfmk/mach/clock_priv_server.c, osfmk/mach/clock_priv_server.h, osfmk/mach/clock_privXtraceMig.c
Generating osfmk/mach/processor_user.c, osfmk/mach/processor.h, osfmk/mach/processor_server.c, osfmk/mach/processor_server.h, osfmk/mach/processorXtraceMig.c
Generating osfmk/mach/host_priv_user.c, osfmk/mach/host_priv.h, osfmk/mach/host_priv_server.c, osfmk/mach/host_priv_server.h, osfmk/mach/host_privXtraceMig.c
Generating osfmk/mach/host_security_user.c, osfmk/mach/host_security.h, osfmk/mach/host_security_server.c, osfmk/mach/host_security_server.h, osfmk/mach/host_securityXtraceMig.c
Generating osfmk/mach/lock_set_user.c, osfmk/mach/lock_set.h, osfmk/mach/lock_set_server.c, osfmk/mach/lock_set_server.h, osfmk/mach/lock_setXtraceMig.c
Generating osfmk/mach/mach_port_user.c, osfmk/mach/mach_port.h, osfmk/mach/mach_port_server.c, osfmk/mach/mach_port_server.h, osfmk/mach/mach_portXtraceMig.c
Generating osfmk/mach/mach_vm_user.c, osfmk/mach/mach_vm.h, osfmk/mach/mach_vm_server.c, osfmk/mach/mach_vm_server.h, osfmk/mach/mach_vmXtraceMig.c
Generating osfmk/mach/mach_host_user.c, osfmk/mach/mach_host.h, osfmk/mach/mach_host_server.c, osfmk/mach/mach_host_server.h, osfmk/mach/mach_hostXtraceMig.c
Generating osfmk/mach/processor_set_user.c, osfmk/mach/processor_set.h, osfmk/mach/processor_set_server.c, osfmk/mach/processor_set_server.h, osfmk/mach/processor_setXtraceMig.c
Generating osfmk/mach/thread_act_user.c, osfmk/mach/thread_act.h, osfmk/mach/thread_act_server.c, osfmk/mach/thread_act_server.h, osfmk/mach/thread_actXtraceMig.c
Generating osfmk/mach/clock_reply_user.c, osfmk/mach/clock_reply.h, osfmk/mach/clock_reply_server.c, osfmk/mach/clock_reply_server.h, osfmk/mach/clock_replyXtraceMig.c
Generating osfmk/device/device_user.c, osfmk/device/device.h, osfmk/device/device_server.c, osfmk/device/device_server.h, osfmk/device/deviceXtraceMig.c
Generating osfmk/UserNotification/UNDReply_user.c, osfmk/UserNotification/UNDReply.h, osfmk/UserNotification/UNDReply_server.c, osfmk/UserNotification/UNDReply_server.h, osfmk/UserNotification/UNDReplyXtraceMig.c
Built target lkm_generate
Built target rtsig
Built target rtsig_h
Building the Linux kernel module
make[4]: Entering directory '/home/user/Downloads/darling/src/external/lkm'
Running kernel version is 5.9.1-desktop-4.mga7
rm -f darling-mach.mod.o
make -C /lib/modules/5.9.1-desktop-4.mga7/build M=/home/user/Downloads/darling/src/external/lkm modules
make[5]: Entering directory '/usr/src/kernel-5.9.1-desktop-4.mga7'
Running kernel version is 5.9.1-desktop-4.mga7
Invoked by kernel build system, building for 5.9.1-desktop-4.mga7
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/mach_types.h:76,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_vm_map.h:38,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:75:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:74:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:140:
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c: In function ‘ipc_kmsg_get’:
/home/user/Downloads/darling/src/external/lkm/darling/debug_print.h:29:55: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 5 has type ‘mach_port_t’ {aka ‘struct ipc_port *’} [-Wformat=]
 # define debug_msg(fmt, ...) if (debug_output) printk("\0015Darling Mach: <%d> " fmt, linux_current->pid, ##__VA_ARGS__)
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:1597:5: note: in expansion of macro ‘debug_msg’
     debug_msg( "- ikm_header->msgh_size: %d, bits: 0x%x rport: 0x%x, lport: 0x%x, reserved: 0x%x, id: %d\n",
     ^~~~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:1597:67: note: format string is defined here
     debug_msg( "- ikm_header->msgh_size: %d, bits: 0x%x rport: 0x%x, lport: 0x%x, reserved: 0x%x, id: %d\n",
                                                                  ~^
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:140:
/home/user/Downloads/darling/src/external/lkm/darling/debug_print.h:29:55: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 6 has type ‘mach_port_t’ {aka ‘struct ipc_port *’} [-Wformat=]
 # define debug_msg(fmt, ...) if (debug_output) printk("\0015Darling Mach: <%d> " fmt, linux_current->pid, ##__VA_ARGS__)
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:1597:5: note: in expansion of macro ‘debug_msg’
     debug_msg( "- ikm_header->msgh_size: %d, bits: 0x%x rport: 0x%x, lport: 0x%x, reserved: 0x%x, id: %d\n",
     ^~~~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:1597:80: note: format string is defined here
     debug_msg( "- ikm_header->msgh_size: %d, bits: 0x%x rport: 0x%x, lport: 0x%x, reserved: 0x%x, id: %d\n",
                                                                               ~^
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c: In function ‘ipc_kmsg_copyin’:
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:3228:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ((kmsg->ikm_header->msgh_bits & MACH_MSGH_BITS_COMPLEX) == 0)
     ^~
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_kmsg.c:3231:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  mr = ipc_kmsg_copyin_body( kmsg, space, map);
  ^~
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_notify.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/port.h:90,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_notify.c:71:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_notify.c:67:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/mach_types.h:76,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.c:35:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.c:30:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.c: In function ‘ipc_get_pthpriority_from_kmsg_voucher’:
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.c:2636:2: warning: ISO C90 forbids variable length array ‘content_data’ [-Wvla]
  uint8_t content_data[content_size];
  ^~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.c: In function ‘ipc_execute_voucher_recipe_command’:
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.c:1509:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if (MACH_VOUCHER_ATTR_KEY_ALL == key) {
      ^
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_voucher.c:1550:2: note: here
  default:
  ^~~~~~~
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_port.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/port.h:90,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_port.c:81:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_port.c:74:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_debug.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/port.h:90,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/vm_types.h:35,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/vm_param.h:75,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_debug.c:73:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_debug.c:67:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_kernelrpc.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/mach_types.h:76,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_kernelrpc.c:34:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_kernelrpc.c:30:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_kernelrpc.c: In function ‘host_create_mach_voucher_trap’:
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_kernelrpc.c:446:3: warning: ISO C90 forbids variable length array ‘krecipes’ [-Wvla]
   uint8_t krecipes[args->recipes_size];
   ^~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_kernelrpc.c: In function ‘mach_voucher_extract_attr_recipe_trap’:
/home/user/Downloads/darling/src/external/lkm/osfmk/ipc/mach_kernelrpc.c:501:3: warning: ISO C90 forbids variable length array ‘krecipe’ [-Wvla]
   uint8_t krecipe[sz];
   ^~~~~~~
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_port.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/port.h:90,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_port.c:80:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/ipc/ipc_port.c:73:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/kern/exception.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/mach_types.h:76,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/kern/exception.c:64:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/kern/exception.c:60:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/kern/sync_sema.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/mach_types.h:76,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/kern/sync_sema.c:46:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/kern/sync_sema.c:40:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
  CC [M]  /home/user/Downloads/darling/src/external/lkm/bsd/uxkern/ux_exception.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/port.h:90,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/exception_types.h:178,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/exception.h:60,
                 from /home/user/Downloads/darling/src/external/lkm/bsd/uxkern/ux_exception.c:51:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/bsd/uxkern/ux_exception.c:42:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
  CC [M]  /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.o
In file included from /home/user/Downloads/darling/src/external/lkm/osfmk/mach/mach_types.h:76,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.h:38,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c:38:
/home/user/Downloads/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
 #define UINTPTR_MAX   UINT64_MAX
 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:7,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct.h:49,
                 from /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c:36:
./include/vdso/limits.h:17: note: this is the location of the previous definition
 #define UINTPTR_MAX ULONG_MAX
 
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c: In function ‘duct_thread_bootstrap’:
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c:223:25: error: ‘struct thread’ has no member named ‘taskwatch’; did you mean ‘c_switch’?
         thread_template.taskwatch = NULL;
                         ^~~~~~~~~
                         c_switch
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c:224:25: error: ‘struct thread’ has no member named ‘saved_importance’; did you mean ‘importance’?
         thread_template.saved_importance = 0;
                         ^~~~~~~~~~~~~~~~
                         importance
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c:229:2: warning: #warning Init thread initialization disabled! [-Wcpp]
 #warning Init thread initialization disabled!
  ^~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c: In function ‘duct_thread_create_internal’:
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c:295:2: warning: #warning compat_uthread disabled [-Wcpp]
 #warning compat_uthread disabled
  ^~~~~~~
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c: In function ‘thread_exception_return’:
/home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.c:901:1: warning: ‘noreturn’ function does return
 }
 ^
make[6]: *** [scripts/Makefile.build:283: /home/user/Downloads/darling/src/external/lkm/osfmk/duct/duct_kern_thread.o] Error 1
make[5]: *** [Makefile:1775: /home/user/Downloads/darling/src/external/lkm] Error 2
make[5]: Leaving directory '/usr/src/kernel-5.9.1-desktop-4.mga7'
make[4]: *** [Makefile:346: default] Error 2
make[4]: Leaving directory '/home/user/Downloads/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:56818: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:56825: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:15738: lkm] Error 2

```

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Mageia Linux | 7.1 |
| GCC | 8.4.0 |
| Clang | 8.0.0 |
| CMake | 3.14.3 |
| Linux Kernel | 5.9.1 |
| Darling | 1470b45ac503443aeb17f94d5751c3d2902c0a08 |

Not sure how to procede from here if i can't compile the Linux Kernel Module... I tried compiling the darling-newlkm package, but that just complained about not finding /usr/bin/xcrun... i'd love to get this working, though.  please advise.  Is this a duplicate of that other "LKM won't build on Kernel 5.9" issue? if so, sorry..

**Comment by HinTak** [comment] 2020-10-23 02:50
Same as https://github.com/darlinghq/darling/issues/884

**Comment by ringtailedfox** [comment] 2020-10-25 03:29
how do i determine the compiler version?

**Comment by ahyattdev** [comment] 2021-02-09 21:29
Closing as duplicate of #884

**Closed by ahyattdev** 2021-02-09 21:29 UTC
