### ISSUE TITLE
Build TextEdit

### ISSUE THREAD

**Issue by TheBrokenRail** [darlinghq/darling#658] opened 2020-02-15 17:53 UTC
Now that GUI apps are (somewhat) working.

**Comment by LubosD** [comment] 2020-02-15 17:55
https://developer.apple.com/library/archive/samplecode/TextEdit/Introduction/Intro.html

**Comment by ahyattdev** [comment] 2020-02-15 19:01
Duplicate of #383

**Closed by ahyattdev** 2020-02-15 19:02 UTC
