### ISSUE TITLE
Illegal instruction 4

### ISSUE THREAD

**Issue by csu-iteam** [darlinghq/darling#385] opened 2018-05-23 13:03 UTC
I have a executable program, which can run on mac os high sierra 10.13.4. And I want to run it on linux, so I install Darling on a Linux server. But when I run it on darling shell , the problem appeared. Illegal instruction 4. The program is over here.
[https://github.com/PikachuHy/xs/blob/master/midi/t2mf](url)

**Comment by bugaevc** [comment] 2018-05-23 13:05
Working link: https://github.com/PikachuHy/xs/blob/master/midi/t2mf

**Comment by ahyattdev** [comment] 2018-05-24 04:17
Just to note, it appears to link to `/usr/lib/libgcc_s.1.dylib`. I'm not familiar with this library, maybe the error is occurring in there.

**Comment by bugaevc** [comment] 2018-05-24 07:51
From a brief exploration, it is indeed hitting an explicit invalid instruction in libsystem_c; but as you can imagine, figuring this out without a working debugger isn't going to be easy; not sure if it's worth the time now

**Comment by LubosD** [comment] 2018-05-24 09:12
Just for reference, this is usually caused by a failed assertion. Some indirect clues may appear in Darling's syslog. This is how Apple makes it "easier" to debug.

**Comment by bugaevc** [comment] 2018-05-24 09:40
I've heard Apple sets Crash Reporter.app as a handler for Mach exceptions, maybe we could do something similar? (Or what's the state of Mach exceptions delivery under Darling?) It'd save me a lot of time if I had a backtrace every time something crashes.

**Comment by LubosD** [comment] 2018-05-24 10:44
@bugaevc The code, as it is implemented, only generates Mach exceptions for Linux SIGSEGVs if another proces has used `ptrace()` (e.g. with `PT_ATTACHEXC`). I don't know what APIs and tricks are used for the Crash Reporter.

**Comment by bugaevc** [comment] 2018-05-24 19:53
It's a `host_info()` call failing during `libSystem_initializer()`.

https://github.com/darlinghq/darling-libpthread/blob/master/src/pthread.c#L1778-L1780

**Comment by LubosD** [comment] 2018-05-24 19:56
That's surprising. Is threading working at all, or is there a serious regression?

**Comment by bugaevc** [comment] 2018-05-24 19:59
I don't normally run 32-bit stuff, so maybe everything is horribly broken there, don't know. But notice that this is not yet spawning a thread, this is just libpthread initializing itself.

**Comment by bugaevc** [comment] 2018-05-25 08:55
It does indeed pass an incorrect reply port. `host_info()` is a MIG routine (declared [here](https://github.com/darlinghq/darling/blob/master/platform-include/mach/mach_host.defs#L90-L93)), so it uses [`mig_get_reply_port()`](https://github.com/darlinghq/darling/blob/master/src/kernel/libsyscall/mach/mig_reply_port.c#L49-L64) to get a reply port.

`mig_get_reply_port()` calls `mach_reply_port()` (a simple Mach trap that allocates a fresh port & returns its recv right) the first time it's invoked, and then caches that port using `_os_tsd_`{`get`, `set`}`_direct(__TSD_MIG_REPLY)`, implemented [here](https://github.com/darlinghq/darling/blob/master/src/kernel/libsyscall/os/tsd.h).

I can confirm `_os_tsd_get_direct()` is returning a bogus value (-137251072), so it looks like something is wrong with the TSD impl on i386 (is it even guaranteed to return 0 the first time?).

**Comment by LubosD** [comment] 2018-05-27 21:11
I've just tried running this binary in my `kernel_macho_loading` branch and it seems to work. I must say, though, I have no idea how to use this program or what it does :-D

```
Darling [/home/lubos]$ ./t2mf  aaa
*** ERROR *** Cannot open 'aaa'!
************* Reason: 2
Darling [/home/lubos]$ ./t2mf     

fkgjbfdkjgbdfjk
Missing MFile - can't continue
```

This branch will soon be merged into `master`, as soon as I ensure that ELF loading really works as it should so the AppKit work doesn't get disrupted.

**Comment by bugaevc** [comment] 2018-06-05 09:54
`kernel_macho_loading` has indeed been merged to `master` (on May 28th), so this should work now 🎉

**Closed by bugaevc** 2018-06-05 09:54 UTC
