### ISSUE TITLE
wget is unable to correctly determine the authenticity of an ssl cert

### ISSUE THREAD

**Issue by Elronnd** [darlinghq/darling#161] opened 2016-10-05 23:25 UTC
Possibly related to #146.  I downloaded go from google's website, to see if it worked, and wget gave me an error that it couldn't verify the cert:

```
darling/home/elronnd/Downloads-32: wget https://storage.googleapis.com/golang/go1.7.1.darwin-amd64.pkg
--2016-10-05 23:20:25--  https://storage.googleapis.com/golang/go1.7.1.darwin-amd64.pkg
Resolving storage.googleapis.com (storage.googleapis.com)... 2607:f8b0:4007:809::2010, 216.58.217.208
Connecting to storage.googleapis.com (storage.googleapis.com)|2607:f8b0:4007:809::2010|:443... failed: Network is unreachable.
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.217.208|:443... connected.
ERROR: cannot verify storage.googleapis.com's certificate, issued by ‘CN=Google Internet Authority G2,O=Google Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to storage.googleapis.com insecurely, use `--no-check-certificate'.
```

**Comment by LubosD** [comment] 2016-10-06 07:14
Hmm, first a little background: Darling uses its own set of certificates, because OS X uses older OpenSSL than current Linux distros, which means cert file names are generated differently. When setting up the prefix, `darling` downloads and installs a package with certificates from here: http://packages.darlinghq.org/org.darlinghq.pkg.OpenSSLCertificates/

Does your `/System/Library/OpenSSL/certs` directory in Darling's prefix contain lots of files?

**Comment by Elronnd** [comment] 2016-10-06 16:58
Yeah, it's pretty filled up.  [Here](http://lpaste.net/245181)'s a pastebin of its contents.

**Comment by bugaevc** [comment] 2017-01-09 13:25
I can reproduce this. My `/System/Library/OpenSSL/certs` contains seemingly the same list as posted by @Elronnd.

See #205 & #206.

**Comment by LubosD** [comment] 2017-01-09 13:54
@bugaevc Could you try to fix it? :-)

**Comment by bugaevc** [comment] 2017-01-10 11:09
From what I can see, `wget` doesn't even try to look in `/System/Library/OpenSSL`, like `curl` does. `wget` only tries to open `/usr/local/etc/ssl/certs/578d5c04.0` and dies on not finding it.

If only Rudix's wget had debug symbols, I could actually trace where that name comes from.

**Comment by LubosD** [comment] 2017-01-10 11:39
Well, if the same path also exists on macOS, then we should symlink it.

**Comment by bugaevc** [comment] 2017-01-10 13:39
> Well, if the same path also exists on macOS, then we should symlink it.

It doesn't! Furthermore, `wget` on macOS fails with the same error:
![screen shot 2017-01-10 at 16 25 48](https://cloud.githubusercontent.com/assets/10091584/21808163/112c7ba2-d753-11e6-919d-db83f97ee44d.png)

:smile: 

I think we can close this as wontfix.

**Comment by LubosD** [comment] 2017-01-10 16:15
Confirmed, so it "works as intended" :-)

**Closed by LubosD** 2017-01-10 16:15 UTC
Labels: bug
