### ISSUE TITLE
Somewhy networking not works at all inside darling

### ISSUE THREAD

**Issue by iamthevoid** [darlinghq/darling#971] opened 2021-05-26 20:21 UTC
**Expected Result**
Network works

**Actual Result**
Nothing happens when i somehow try to reach network and web. When i try to run next commands i receive nothing, but blinking cursor on next line, like hang, but responsive:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
`xcode-select --install`
or even
`curl www.google.com`

`ifconfig` produces next result
```
Darling [/Volumes/SystemRoot/home/iam]$ ifconfig
Passing thru unhandled ioctl 0xC0206917 on fd 3
Passing thru unhandled ioctl 0xC0206933 on fd 3
Passing thru unhandled ioctl 0xC02069CC on fd 3
lo: flags=0<>
Passing thru unhandled ioctl 0xC020695B on fd 3
Passing thru unhandled ioctl 0xC120693F on fd 3
Passing thru unhandled ioctl 0xC020693F on fd 3
        lladdr 00:00:00:00:00:00 
        inet 127.0.0.1 netmask 0xff000000 
Passing thru unhandled ioctl 0xC02469C9 on fd 3
Passing thru unhandled ioctl 0xC06069C1 on fd 3
Passing thru unhandled ioctl 0xC020697F on fd 3
Passing thru unhandled ioctl 0xC02C6948 on fd 3
Passing thru unhandled ioctl 0xC028697B on fd 3
Passing thru unhandled ioctl 0xC028697B on fd 3
Passing thru unhandled ioctl 0xC0206947 on fd 3
Passing thru unhandled ioctl 0xC02069C5 on fd 3
Passing thru unhandled ioctl 0xC030694C on fd 5
ifconfig: ioctl(SIOCGIFINFO_IN6): Inappropriate ioctl for device
Passing thru unhandled ioctl 0xC331693D on fd 3
Passing thru unhandled ioctl 0xC0206917 on fd 3
Passing thru unhandled ioctl 0xC0206933 on fd 3
Passing thru unhandled ioctl 0xC02069CC on fd 3
enp3s0: flags=0<>
Passing thru unhandled ioctl 0xC020695B on fd 3
Passing thru unhandled ioctl 0xC120693F on fd 3
Passing thru unhandled ioctl 0xC020693F on fd 3
        lladdr 90:f6:52:ac:37:c0 
        inet 192.168.100.11 netmask 0xffffff00 
Passing thru unhandled ioctl 0xC02469C9 on fd 3
Passing thru unhandled ioctl 0xC06069C1 on fd 3
Passing thru unhandled ioctl 0xC020697F on fd 3
Passing thru unhandled ioctl 0xC02C6948 on fd 3
Passing thru unhandled ioctl 0xC028697B on fd 3
Passing thru unhandled ioctl 0xC028697B on fd 3
Passing thru unhandled ioctl 0xC0206947 on fd 3
Passing thru unhandled ioctl 0xC02069C5 on fd 3
Passing thru unhandled ioctl 0xC030694C on fd 5
ifconfig: ioctl(SIOCGIFINFO_IN6): Inappropriate ioctl for device
Passing thru unhandled ioctl 0xC331693D on fd 3
Passing thru unhandled ioctl 0xC0206917 on fd 3
Passing thru unhandled ioctl 0xC0206933 on fd 3
Passing thru unhandled ioctl 0xC02069CC on fd 3
wlp4s0: flags=0<>
Passing thru unhandled ioctl 0xC020695B on fd 3
Passing thru unhandled ioctl 0xC120693F on fd 3
Passing thru unhandled ioctl 0xC020693F on fd 3
        lladdr 28:c6:3f:99:8d:97 
        inet 192.168.100.9 netmask 0xffffff00 
Passing thru unhandled ioctl 0xC02469C9 on fd 3
Passing thru unhandled ioctl 0xC06069C1 on fd 3
Passing thru unhandled ioctl 0xC020697F on fd 3
Passing thru unhandled ioctl 0xC02C6948 on fd 3
Passing thru unhandled ioctl 0xC028697B on fd 3
Passing thru unhandled ioctl 0xC028697B on fd 3
Passing thru unhandled ioctl 0xC0206947 on fd 3
Passing thru unhandled ioctl 0xC02069C5 on fd 3
Passing thru unhandled ioctl 0xC030694C on fd 5
ifconfig: ioctl(SIOCGIFINFO_IN6): Inappropriate ioctl for device
Passing thru unhandled ioctl 0xC331693D on fd 3
```

**Steps To Reproduce**
There will be not the steps to reproduce, but my actions and thougths. 
At first: current darling installation is not the first installation on that system. Previos versions was uninstalled with 
```
$ cd darling
$ tools/uninstall
```
When i was writing `Actual Result` block i remembered that when i installed darling first time `xcode-select --install` worked well. 

I have a feeling that something from first install (some lock file) leaves in my system and blocks internet connection. Have you any idea what can it be? 

**System Information**
```
[iam@thevoid ~]$ screenfetch

 ██████████████████  ████████     iam@thevoid
 ██████████████████  ████████     OS: Manjaro 21.0.5 Ornara
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.36-2-MANJARO
 ██████████████████  ████████     Uptime: 24m
 ████████            ████████     Packages: 1512
 ████████  ████████  ████████     Shell: bash 5.1.8
 ████████  ████████  ████████     Resolution: 3840x2160
 ████████  ████████  ████████     DE: KDE 5.82.0 / Plasma 5.21.5
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze-Dark [GTK2], Breeze [GTK3]
 ████████  ████████  ████████     Icon Theme: breeze-dark
 ████████  ████████  ████████     Disk: 1,8T / 2,7T (70%)
 ████████  ████████  ████████     CPU: Intel Core i7-7700HQ @ 8x 3.8GHz [76.0°C]
 ████████  ████████  ████████     GPU: GeForce GTX 1070
                                  RAM: 3361MiB / 31992MiB

```

```
[iam@thevoid ~]$ inxi -Fxxxz
System:    Kernel: 5.10.36-2-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 Desktop: KDE Plasma 5.21.5 tk: Qt 5.15.2 
           info: latte-dock wm: kwin_x11 vt: 1 dm: SDDM Distro: Manjaro Linux base: Arch Linux 
Machine:   Type: Laptop System: GIGABYTE product: P56X v: N/A serial: <filter> 
           Mobo: GIGABYTE model: P56X serial: <filter> UEFI: American Megatrends v: FA09 date: 07/24/2018 
Battery:   ID-1: BAT1 charge: 91.2 Wh (100.0%) condition: 91.2/91.2 Wh (100.0%) volts: 12.5 min: 11.4 model: GIGABYTE P56X 
           type: Li-ion serial: N/A status: Full 
CPU:       Info: Quad Core model: Intel Core i7-7700HQ bits: 64 type: MT MCP arch: Kaby Lake rev: 9 cache: L2: 6 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 44817 
           Speed: 901 MHz min/max: 800/3800 MHz Core speeds (MHz): 1: 901 2: 901 3: 900 4: 900 5: 900 6: 900 7: 900 8: 900 
Graphics:  Device-1: Intel HD Graphics 630 vendor: Gigabyte driver: i915 v: kernel bus-ID: 00:02.0 chip-ID: 8086:591b 
           class-ID: 0300 
           Device-2: NVIDIA GP104M [GeForce GTX 1070 Mobile] vendor: Gigabyte driver: nvidia v: 460.80 bus-ID: 01:00.0 
           chip-ID: 10de:1ba1 class-ID: 0300 
           Device-3: Sunplus Innovation HD WebCam type: USB driver: uvcvideo bus-ID: 1-9:7 chip-ID: 1bcf:2c6b class-ID: 0e02 
           Display: x11 server: X.Org 1.20.11 compositor: kwin_x11 driver: loaded: modesetting,nvidia 
           resolution: 3840x2160~60Hz s-dpi: 190 
           OpenGL: renderer: GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 460.80 direct render: Yes 
Audio:     Device-1: Intel CM238 HD Audio vendor: Gigabyte driver: snd_hda_intel v: kernel bus-ID: 00:1f.3 chip-ID: 8086:a171 
           class-ID: 0403 
           Sound Server-1: ALSA v: k5.10.36-2-MANJARO running: yes 
           Sound Server-2: JACK v: 1.9.18 running: no 
           Sound Server-3: PulseAudio v: 14.2 running: yes 
           Sound Server-4: PipeWire v: 0.3.28 running: yes 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte driver: r8169 v: kernel 
           port: d000 bus-ID: 03:00.0 chip-ID: 10ec:8168 class-ID: 0200 
           IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
           Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: d000 bus-ID: 04:00.0 chip-ID: 8086:24fd 
           class-ID: 0280 
           IF: wlp4s0 state: up mac: <filter> 
Bluetooth: Device-1: Intel Bluetooth wireless interface type: USB driver: btusb v: 0.8 bus-ID: 1-4:3 chip-ID: 8087:0a2b 
           class-ID: e001 
           Report: rfkill ID: hci0 rfk-id: 1 state: up address: see --recommends 
Drives:    Local Storage: total: 2.74 TiB used: 1.77 TiB (64.6%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 PRO 512GB size: 476.94 GiB speed: 31.6 Gb/s lanes: 4 
           rotation: SSD serial: <filter> rev: 1B2QEXP7 temp: 48.9 C scheme: GPT 
           ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 970 EVO Plus 500GB size: 465.76 GiB speed: 31.6 Gb/s lanes: 4 
           rotation: SSD serial: <filter> rev: 2B2QEXM7 temp: 50.9 C scheme: GPT 
           ID-3: /dev/sda vendor: Seagate model: ST2000LM015-2E8174 size: 1.82 TiB speed: 6.0 Gb/s rotation: 5400 rpm 
           serial: <filter> rev: SDM1 scheme: MBR 
Partition: ID-1: / size: 444.72 GiB used: 251.65 GiB (56.6%) fs: ext4 dev: /dev/nvme0n1p2 
           ID-2: /boot/efi size: 99.4 MiB used: 24.1 MiB (24.2%) fs: vfat dev: /dev/nvme0n1p1 
Swap:      ID-1: swap-1 type: partition size: 24 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/nvme0n1p3 
Sensors:   System Temperatures: cpu: 55.0 C mobo: 29.8 C gpu: nvidia temp: 66 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 265 Uptime: 24m wakeups: 1 Memory: 31.24 GiB used: 3.29 GiB (10.5%) Init: systemd v: 247 Compilers: 
           gcc: 10.2.0 clang: 11.1.0 Packages: pacman: 1512 Shell: Bash v: 5.1.8 running-in: konsole inxi: 3.3.04 
```

**Comment by facekapow** [comment] 2021-05-26 21:30
Actually, I'm pretty sure this is also #967. Check if it is by running `launchctl list`. If `launchd` says that `syslogd` has status code `-4`, then the problem is not with networking, it's actually #967.

**Comment by iamthevoid** [comment] 2021-05-27 04:57
@facekapow You correct
```
Darling [/Volumes/SystemRoot/usr/bin/cshell]$ launchctl list
PID     Status  Label
47      -       0x7ff0d9400600.anonymous.launchctl
31      -       0x7ff0f9404d90.anonymous.shellspawn
32      -       0x7ff0f9404b10.anonymous.bash
-       0       com.apple.periodic-daily
-       0       com.apple.periodic-weekly
-       0       com.apple.trustd
18      -       com.apple.notifyd
-       0       com.apple.FileCoordination
-       -4      com.apple.syslogd
14      -       com.apple.securityd
24      -       com.apple.aslmanager
-       0       com.apple.newsyslog
15      -       org.darlinghq.iokitd
16      -       org.darlinghq.shellspawn
-       0       org.cups.cupsd
17      -       com.apple.memberd
-       0       com.apple.periodic-monthly
-       0       com.apple.var-db-dslocal-backup
11      -       com.apple.launchctl.System
```

**Comment by facekapow** [comment] 2021-05-27 12:03
Okay, closing in favor of #967 (that's the real issue here).

**Closed by facekapow** 2021-05-27 12:03 UTC
