### ISSUE TITLE
Cannot start shell (username problem)

### ISSUE THREAD

**Issue by Martheus** [darlinghq/darling#763] opened 2020-04-24 16:56 UTC
Hello, I just compiled Darling with LKM, then installed on Ubuntu 20.04 with 5.4.0-26-generic kernel and rebooted, but its giving me weird error when I'm trying to go to the Darling shell. I tried it also on other kernels (5.4.0-21, 5.4.0-24, 5.4.0-25 generic) but with no difference. Thank you for any help.

`martheus@Lenovo-Studio:~$ darling shell`
`Cannot determine your user name`
`Cannot open mnt namespace file: No such file or directory`
`martheus@Lenovo-Studio:~$ sudo bash`
`root@Lenovo-Studio:/# darling shell`
`Loaded the kernel module`
`Cannot determine your user name`
`Cannot open mnt namespace file: No such file or directory`
`root@Lenovo-Studio:/#`

**Comment by bugaevc** [comment] 2020-04-24 16:59
`echo $USER`?

**Comment by HinTak** [comment] 2020-04-24 17:20
Looks similar to https://github.com/darlinghq/darling/issues/715 , and see workaround there...

**Comment by Martheus** [comment] 2020-04-24 17:52
echo $USER returns my normal username.
Thanks a lot HinTak for link to #715 - workaround works. :)
I'm trying to figure out why is this happening only in desktop terminal and not in system console...

**Comment by bugaevc** [comment] 2020-04-25 15:04
Closing as duplicate of #715 then

**Closed by bugaevc** 2020-04-25 15:04 UTC
