### ISSUE TITLE
Darling shell not launching

### ISSUE THREAD

**Issue by Wolverine327** [darlinghq/darling#1446] opened 2023-10-25 21:57 UTC
**Result**
```
$ darling shell 
Bootstrapping the container with launchd...
libEGL warning: DRI2: failed to authenticate
Error connecting to shellspawn session
Error receiving reply from shellsession: No such file or directory
```

**```strace``` Output**
Run ```sudo strace -f -u $USER darling shell```
```
execve("/usr/local/bin/darling", ["darling", "shell"], 0x7fffe3233380 /* 18 vars */) = 0
access("/etc/suid-debug", F_OK)         = -1 ENOENT (No such file or directory)
brk(NULL)                               = 0x559cdce7f000
fcntl(0, F_GETFD)                       = 0
fcntl(1, F_GETFD)                       = 0
fcntl(2, F_GETFD)                       = 0
access("/etc/suid-debug", F_OK)         = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f965eb3c000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=100303, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 100303, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f965eb23000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220x\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1926256, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1974096, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f965e941000
mmap(0x7f965e967000, 1396736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f965e967000
mmap(0x7f965eabc000, 344064, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17b000) = 0x7f965eabc000
mmap(0x7f965eb10000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1cf000) = 0x7f965eb10000
mmap(0x7f965eb16000, 53072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f965eb16000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f965e93e000
arch_prctl(ARCH_SET_FS, 0x7f965e93e740) = 0
set_tid_address(0x7f965e93ea10)         = 45527
set_robust_list(0x7f965e93ea20, 24)     = 0
rseq(0x7f965e93f060, 0x20, 0, 0x53053053) = 0
mprotect(0x7f965eb10000, 16384, PROT_READ) = 0
mprotect(0x559cdbd49000, 4096, PROT_READ) = 0
mprotect(0x7f965eb6e000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f965eb23000, 100303)          = 0
geteuid()                               = 0
getuid()                                = 1000
getgid()                                = 1000
setuid(0)                               = 0
setgid(0)                               = 0
getrandom("\x76\x1d\xcd\xb1\x5d\x09\x88\xd4", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x559cdce7f000
brk(0x559cdcea0000)                     = 0x559cdcea0000
getcwd("/home/kali/darling/build", 4096) = 25
newfstatat(AT_FDCWD, "/root/.darling", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/root/.darling", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
write(2, "You do not own the prefix direct"..., 37You do not own the prefix directory.
) = 37
exit_group(1)                           = ?
+++ exited with 1 +++
```

**``dmesg`` Output**
Run ```dmesg | grep 'overlay\|darling'```
```
[ 1605.630486] overlayfs: upperdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
[ 1605.630493] overlayfs: workdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
[ 1920.566567] overlayfs: upperdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
[ 1920.566575] overlayfs: workdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
[ 2124.000644] overlayfs: upperdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
[ 2124.000651] overlayfs: workdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
```

**System Information**
What system are you running?

| Software | Version |
| --- | --- |
| Linux Kernel | 6.5.0-kali3-amd64|
| Darling | 7b2aa573bdd9b3ce143ef2f0acf54841e51b9895 |

**Comment by MagicalTux** [comment] 2023-10-26 15:42
I'm guessing this is a duplicate of #1443

@Wolverine327 Try building Darling at commit 47c204a2434b71297becf92d5457e5f80c251c51 and see if that helps with your issue

**Comment by facekapow** [comment] 2023-11-02 01:31
Yeah, it's a duplicate; closing in favor of that issue.

**Closed by facekapow** 2023-11-02 01:31 UTC
