### ISSUE TITLE
[TestFunction className]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by CuriousTommy** [darlinghq/darling#519] opened 2019-05-24 16:49 UTC
While I was doing some more testing with `CNLabeledValue`, I happen to stumble upon a bug whenever I call `[MyClassName className]`. I would always get this error message:
```
$ ./ObjectiveCPlayground 
2019-05-24 09:36:37.721 ObjectiveCPlayground[27:3e8] Terminating app due to uncaught exception 'NSException', reason: '+[TestFunction className]: unrecognized selector sent to instance 0x7ffff7ff8318'
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6 (core dumped)
```
On a real Mac, this should print out the name of the class.

Attached below is the source code and binary file that was used to test this.
[className.zip](https://github.com/darlinghq/darling/files/3217832/className.zip)

**Comment by bugaevc** [comment] 2019-05-24 17:00
Would you like to try to write it and submit another PR?

I suppose it should go [here](https://github.com/darlinghq/darling-corefoundation/blob/master/NSObject.m), but ideally you should check whether Apple have it in libobjc4, Core Foundation or Foundation.

**Comment by CuriousTommy** [comment] 2019-05-24 17:12
Sure, I think this should not be too hard to implement.

**Comment by CuriousTommy** [comment] 2019-05-24 21:22
[Going from the website](https://developer.apple.com/documentation/objectivec/nsobject/1411337-classname?language=objc), this variable comes from the Foundation framework. With that in mind, I am going to assume that I need to edit [this header file](https://github.com/darlinghq/darling-foundation/blob/master/include/Foundation/NSObject.h#L34) and create an init function in [the .m file](https://github.com/darlinghq/darling-foundation/blob/master/src/NSObject%2BNSComparisonMethods.m).

One thing I am concerned about is how I will be able to get the object's class name. Looking at the code you link, I could try using the `object_getClassName` function.

@bugaevc I want to make sure I am on the right track. I am still new to the whole Foundation vs CoreFoundation stuff.

**Comment by CuriousTommy** [comment] 2019-05-25 02:45
One thing I don't understand is why are the NS objects located in the Core Foundation repository? It seem like they should belong in the Foundation repository instead.

Or at least that was Apple's documentation seems to imply.

**Comment by bugaevc** [comment] 2019-05-25 07:22
Yes, this is a bit weird. "Officially" `NSObject`, `NSString`, `NSArray`, etc. are all in Foundation (although it looks like the docs do say `NSObject` is in objc runtime).

Actually, `NSObject` proper is in objc runtime (https://github.com/darlinghq/darling-objc4/blob/master/runtime/NSObject.mm), and CF adds some extensions to it.

Some toll-free bridged (TFBed for short) classes like `NSString` are themselves in CF, but have large parts of their functionality implemented in F (in a category). Some classes like `NSUserDefaults` have _all_ of their functionality in F while still having the class itself in CF.

This is not pretty, but this is how Apple does it, and we keep it the same way in Darling. The bottom line is you cannot trust what the Apple docs say about where a class or method is. Again, you can use `nm` on Apple's framework binaries to figure out where a class or a method really is.

> I could try using the `object_getClassName` function.

That's one possibility, but if I understand it right, both

```objc
[Foo className]`
```
and
```objc
Foo *foo = [Foo foo];
[foo className]
```

should return `@"Foo"`, which makes me suspect `[object class]` is involved.

**Comment by bugaevc** [comment] 2019-05-25 07:48
Guess I haven't answered the actual question why. If you look at how `NSObject` is used in objc runtime, you'll find that it's used for being a superclass of class `Protocol`, for ARC compatibility, and in some other ARC-related magic.

**Comment by CuriousTommy** [comment] 2019-05-26 03:12
```
/home/user/Downloads/darling/src/external/cocotron/CoreData/include/CoreData/NSEntityDescription.h:13:15: error: duplicate member '_className'
    NSString *_className;
              ^
/home/user/Downloads/darling/src/external/objc4/runtime/include/objc/NSObject.h:55:15: note: previous declaration is here
    NSString *_className;

```
I noticed that  `NSString *_className` is declated in NSEntityDescription.h; however, [Apple's docs](https://developer.apple.com/documentation/coredata/nsentitydescription?language=objc) nor the [nm output of CoreData](https://pastebin.com/g0NfmiKJ) has any reference to `className`.

I believe that it should not belong in NSEntityDescription.h.

**Comment by CuriousTommy** [comment] 2019-05-26 05:17
So this is how I went about implementing className:
**NSObject.h**
```
@interface NSObject <NSObject> {
    Class isa  OBJC_ISA_AVAILABILITY;
    NSString *_className;
}
...
@property(class,readonly,copy) NSString *className;

@end
```
**NSObject.mm**
```
@implementation NSObject

static NSString *_className;
...
+ (void)initialize {
    _className = [self class];
    _className = [_className copy];
}
...
+ (NSString *)className {
    return _className;
}

- (NSString *)className {
    return _className;
}
```


But it seems like my current implementation doesn't return the right value...
```
2019-05-25 22:03:47.477 Messing With NSObject[23:3e8] __NSArrayI
2019-05-25 22:03:47.477 Messing With NSObject[23:3e8] (null)
2019-05-25 22:03:47.477 Messing With NSObject[23:3e8] (null)
2019-05-25 22:03:47.477 Messing With NSObject[23:3e8] NSObject
2019-05-25 22:03:47.478 Messing With NSObject[23:3e8] NSThread
2019-05-25 22:03:47.478 Messing With NSObject[23:3e8] NSThread
2019-05-25 22:03:47.478 Messing With NSObject[23:3e8] NSArray
2019-05-25 22:03:47.478 Messing With NSObject[23:3e8] NSThread
2019-05-25 22:03:47.478 Messing With NSObject[23:3e8] NSThread
```
I think I understand why NSThread is showing, but I am not sure how I should go about fixing this issue...

---

Here is the test code if you want to see how it works:
```
#import <Foundation/Foundation.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSObject *dummy = [[[NSArray alloc] init] autorelease];
        // insert code here...
        NSLog(@"%@", [dummy class]);
        NSLog(@"%@", [dummy className]);
        NSLog(@"%@", dummy.className);
        
        NSLog(@"%@", NSObject.class);
        NSLog(@"%@", [NSObject className]);
        NSLog(@"%@", NSObject.className);
        
        NSLog(@"%@", NSArray.class);
        NSLog(@"%@", [NSArray className]);
        NSLog(@"%@", NSArray.className);
    }
    
    return 0;
}
```

**Comment by bugaevc** [comment] 2019-05-26 06:35
No no no no no, this is very wrong.

You cannot just add another instance variable to `NSObject` like that. `NSObject` is a fundamental class, and a lot of things (such as TFB) rely on it having exactly one ivar (which used to be `isa`, and now is "something objc runtime can convert to and from `isa`").

And in general, do not change Apple's code (including objc runtime) without a good reason. Usually Apple code already does everything it should do and the problem is elsewhere (one notable exception is TFB, which Apple has removed from the open source version of CF).

> `static NSString *_className;`

This creates *another* thing named `_className`, in addition to the `_className` ivar you've added. I'm not even sure which one will get used below.

And there is one "copy" of this static variable, not one per class, so each new class will override the previous value (assuming it will access the variable and not the `ivar`).

> _className = [self class];

This will make `_className` the class itself, not its name. The class is of type `Class`, its name is of type `NString *`. And since this would run in a class, not instance, method, `[self class]` would just return `self`.

Now, to point you in the right direction: you don't need to store anything to implement this (so, no new instance variables and no static variables). You can get the class of `self` using `[self class]`, and there exists a handy function to get the name of a class as an `NSString`.

**Comment by CuriousTommy** [comment] 2019-05-26 14:21
> Now, to point you in the right direction: you don't need to store anything to implement this (so, no new instance variables and no static variables). You can get the class of self using [self class], and there exists a handy function to get the name of a class as an NSString.

The part that confused me is the fact that [Apple's dev website](https://developer.apple.com/documentation/objectivec/nsobject/1411337-classname?language=objc) has `className` as a `@property`.

From what I understand about `@property`, it should create a setter (if `readwrite`), getter, and a variable for the class.

Can you use a property without providing a variable (`NSString *_className`) for the class?

**Comment by bugaevc** [comment] 2019-05-26 14:58
> Can I use a property without providing a variable (NSString *_className) for the class?

Of course. A property is a getter/setter pair (or just a getter for readonly properties), not an ivar. It's when you synthesize (or auto-synthesize) a property that the compiler creates an ivar for you. So

```objc
// in @interface
@property (readonly, copy) NSString *className;

// in @implementation
- (NSString *) className {
    ...
}
```
should work.

I would even prefer if instead of declaring it as a `@property` we just declared the getter method:

```objc
// in @interface
- (NSString *) className;
```

But there is a difference; I believe `@property` would generate a `objc_property_t` accessible at runtime via reflection, and a getter would not. Perhaps you could check whether Apple's `NSObject` has `className` as `objc_property_t`.

**Comment by CuriousTommy** [comment] 2019-05-26 22:05
> Apple's NSObject has className as objc_property_t.

After a quick test, I can confirm that it does have it.

> there exists a handy function to get the name of a class as an NSString.

I am going to assume that it is [NSStringFromClass](https://developer.apple.com/documentation/foundation/1395143-nsstringfromclass?language=objc)? Also, I would not have to worry about using autorelease since NSStringFromClass would already do that for me, right?

My only concern is how I can import this function. I found out that you can't import the Foundation header without breaking stuff.

**Comment by bugaevc** [comment] 2019-05-27 05:55
> I am going to assume that it is NSStringFromClass? Also, I would not have to worry about using autorelease since NSStringFromClass would already do that for me, right?

Yes and yes.

> My only concern is how I can import this function. I found out that you can't import the Foundation header without breaking stuff.

Don't import `<Foundation/Foundation.h>`, import the one header you need, in this case `<Foundation/NSObjCRuntime.h>`.

**Comment by CuriousTommy** [comment] 2019-05-27 15:48
After linking `<Foundation/NSObjCRuntime.h>`, I get this issue:
```
[ 29%] Linking CXX shared library libobjc.A.dylib
clang-8: warning: argument unused during compilation: '-nostdinc' [-Wunused-command-line-argument]
clang-8: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
ld: warning: -rpath cannot be used with dylibs that will be in the dyld shared cache
Undefined symbols for architecture i386:
  "_NSStringFromClass", referenced from:
      +[NSObject className] in NSObject.o
      -[NSObject className] in NSObject.o
ld: symbol(s) not found for architecture i386
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/external/objc4/runtime/CMakeFiles/objc.dir/build.make:172: src/external/objc4/runtime/libobjc.A.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:12051: src/external/objc4/runtime/CMakeFiles/objc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by bugaevc** [comment] 2019-05-27 17:37
Perhaps Apple actually have it in F, that's why I said

> ideally you should check whether Apple have it in libobjc4, Core Foundation or Foundation.

if it is indeed inside CF, then you cannot use `NSStringFromClass`. You cannot really create an `NSString` from CF either (because the initializers are in F, and what if the program only links to CF?); instead you manually create a `CFString` and TFB-cast it to `NSString` (let me know if I need to expand on that — do you understand what TFB is and how it works, and why it will help here?)

**Comment by CuriousTommy** [comment] 2019-05-27 18:33
> do you understand what TFB is and how it works

It's probably best if you explain what TFB is, but from what I understand, TFB (or Toll-Free Bridging) where you can switch between Apple's Objective C class and their C counterpart.

Ex: If I want to cast CFString to NSString, I would do the following.
```
CFString my_cfstring = ...;
NSString *my_nstring = (__bridge NSString *)my_cfstring;
```

> why it will help here?

I get that if we are not allow to use the Foundation stuff, we would need to use the Core Foundation stuff. But I don't fully understand why we are not allow to use the foundation stuff in the first place.

> Perhaps Apple actually have it in F, that's why I said... if it is indeed inside CF, then you cannot use NSStringFromClass

This is the part I don't really understand. When I use `nm`, Am I looking for something that resembles `+[NSObject(...) className]` and `-[NSObject(...) className]`? Also, where would library for libobjc4 be located on a real Mac?

**Comment by bugaevc** [comment] 2019-05-27 19:26
> It's probably best if you explain what TFB is, but from what I understand, TFB (or Toll-Free Bridging) where you can switch between Apple's Objective C class and their C counterpart.

Yes. From a user viewpoint, TFB is some deep magic that allows you to directly cast between (some) objc / Foundation types and their C / CoreFoundation counterparts. The cast is "toll free" (meaning zero cost), it only exists at compile time to satisfy the typechecker of the compiler; at runtime, you're just using a very same pointer both as e.g. a `CFStringRef` and `NSString *`.

This is *not* a compiler-assisted conversion. In C++, you can do this:

```c++
(std::string) "foo"
```

and although this looks like a cast, the compiler will actually insert a call to `std::string`'s constructor, which will make a copy of the passed in C string. This is *not* what happens with TFB;

```objc
(NSString *) myCFStr
```

compiles down to nothing, the very same pointer is usable both as a `CFStringRef` and an `NSString *`.

This is more complicated than it could be for two reasons:
* `NSString` is a class cluster & an abstract class; you can actually subclass it, implement the two required methods, and get a perfectly usable `NSString`, which can then also be TFBed to `CFString` just like any other
* it is possible for a program to only use CF but not F; `CFString`s must work without Foundation or `NSString`s whatsoever (so it's not possible to simply make `CFString` a wrapper over `NSString`).

The way this is implemented:
* each "real" `CFStringRef` (created by CF) has an `isa` pointing to `__NSCFString`, an objc class whose methods wrap the corresponding `CFString` functions
* all the `CFString` methods check whether the passed in string is actually an instance of some other objc class rather than a "real" `CFString` and if so, invoke the corresponding objc methods on it

There are a lot of details about this and note I'm only using `NSString`/`CFString` as an example; there are many TFBed class pairs.

> I get that if we are not allow to use the Foundation stuff, we would need to use the Core Foundation stuff. 

Yes, the idea is that you can use `CFString` in CF code, and if the program also uses F (which it should if it calls `className` and expects to get back an `NSString`) that `CFString` will also be a valid `NSString *` thanks to TFB.

> This is the part I don't really understand. When I use `nm`, Am I looking for something that resembles `+[NSObject(...) className]` and `-[NSObject(...) className]`?

Yes

> Also, where would the library for libobjc4 be located on a real Mac?

`/usr/lib/libobjc.A.dylib` (same as [on Darling](https://github.com/darlinghq/darling-objc4/blob/master/runtime/CMakeLists.txt#L101))

**Comment by CuriousTommy** [comment] 2019-05-27 23:18
After looking through the `nm` output. `className`actually part of another class (`NSScriptClassDescription`). This class get applied to NSObject using Categories. It is also part of the `Foundation.framework`.

```
0000000000070dce t -[NSObject(NSScriptClassDescription) className]
```

Looking at [the header file](https://github.com/darlinghq/darling-foundation/blob/master/include/Foundation/NSScriptClassDescription.h), it looks like I am going to have to do a lot more then just implement className... I am also going to have to do some reading into how Categories work exactly.

**Comment by bugaevc** [comment] 2019-05-28 06:36
> it looks like I am going to have to do a lot more then just implement className...

> If I can get away with a partial implementation, I could try to implement the parts I only need.

Sure, you don't have to implement all of it at once. Implement `className` for now, and maybe someone — maybe you — will implement the rest of `NSScriptClassDescription` later.

**Comment by CuriousTommy** [comment] 2019-05-29 21:46
I opened a PR: https://github.com/darlinghq/darling-foundation/pull/2

**Comment by ahyattdev** [comment] 2019-05-29 23:27
Merged that PR 👍

**Closed** 2019-05-30 00:05 UTC
