### ISSUE TITLE
[Question] Compatibility list

### ISSUE THREAD

**Issue by Hexality** [darlinghq/darling#1009] opened 2021-08-14 15:24 UTC
Hi, came to ask if there's any software compatibility list for DarlingHQ already.
I wanted to test some but every single one of that softwares I tried gave me LSOpenURLsWithRole STUB error or dyld, and because fo that I decided to come here and ask.
Is there any known working gui apps? 
> Running on **Ubuntu 20.04 for Windows Subsystem for Linux** with GUI programs supported with both advanced graphical support (opengl) and audio (Pulseaudio).
![image](https://user-images.githubusercontent.com/17398632/129451409-69e5ea7d-6bba-4de2-a7b5-13c847d5493a.png)

**Comment by JCWasmx86** [comment] 2021-08-14 19:05
(Just a user)

At the moment a lot of commandline applications work and only the most trivial GUIs (E.g. an empty window)

**Comment by Hexality** [comment] 2021-08-14 19:36
brew still refuses to install though

**Comment by facekapow** [comment] 2022-01-25 15:21
Duplicate of #162

**Closed by facekapow** 2022-01-25 15:21 UTC
Labels: Duplicate
