### ISSUE TITLE
make lkm fails on alpine:3.15 (kernel 5.10)

### ISSUE THREAD

**Issue by maslick** [darlinghq/darling#1079] opened 2021-12-28 13:03 UTC
**Build Log**
What is the build error?
```
bash-5.1# cat > /etc/apk/repositories << EOF; $(echo)

http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/main
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing

EOF

bash-5.1 # apk update && apk add linux-lts-dev cmake clang bison flex xz fuse-dev pkgconfig linux-headers libcap git python2 python3 glu-dev \
cairo-dev mesa-dev tiff-dev freetype-dev libxml2-dev fontconfig-dev libbsd-dev libxrandr-dev libxcursor-dev \
giflib-dev pulseaudio-dev ffmpeg-dev dbus-dev libxkbfile-dev openssl-dev libexecinfo-dev make gcc g++ xdg-user-dirs
....

bash-5.1# git clone --recursive https://github.com/darlinghq/darling.git
bash-5.1# cd darling
bash-5.1# mkdir build && cd build
bash-5.1# cmake -DFULL_BUILD=OFF -DTARGET_i386=OFF ..
....

bash-5.1# make -j16
....

bash-5.1#  make install -j16
....
```

Everything is good until I build ``lkm``:
```
bash-5.1# make lkm
Built target rtsig
Built target rtsig_h
Built target migcom
Built target migexe
Generating osfmk/mach/upl_user.c, osfmk/mach/upl.h, osfmk/mach/upl_server.c, osfmk/mach/upl_server.h, osfmk/mach/uplXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/host_notify_reply_user.c, osfmk/mach/host_notify_reply.h, osfmk/mach/host_notify_reply_server.c, osfmk/mach/host_notify_reply_server.h, osfmk/mach/host_notify_replyXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/vm32_map_user.c, osfmk/mach/vm32_map.h, osfmk/mach/vm32_map_server.c, osfmk/mach/vm32_map_server.h, osfmk/mach/vm32_mapXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/mach_notify_user.c, osfmk/mach/mach_notify.h, osfmk/mach/mach_notify_server.c, osfmk/mach/mach_notify_server.h, osfmk/mach/mach_notifyXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/mach_voucher_attr_control_user.c, osfmk/mach/mach_voucher_attr_control.h, osfmk/mach/mach_voucher_attr_control_server.c, osfmk/mach/mach_voucher_attr_control_server.h, osfmk/mach/mach_voucher_attr_controlXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/memory_entry_user.c, osfmk/mach/memory_entry.h, osfmk/mach/memory_entry_server.c, osfmk/mach/memory_entry_server.h, osfmk/mach/memory_entryXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/memory_object_control_user.c, osfmk/mach/memory_object_control.h, osfmk/mach/memory_object_control_server.c, osfmk/mach/memory_object_control_server.h, osfmk/mach/memory_object_controlXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/memory_object_user.c, osfmk/mach/memory_object.h, osfmk/mach/memory_object_server.c, osfmk/mach/memory_object_server.h, osfmk/mach/memory_objectXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/memory_object_default_user.c, osfmk/mach/memory_object_default.h, osfmk/mach/memory_object_default_server.c, osfmk/mach/memory_object_default_server.h, osfmk/mach/memory_object_defaultXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/mach_voucher_user.c, osfmk/mach/mach_voucher.h, osfmk/mach/mach_voucher_server.c, osfmk/mach/mach_voucher_server.h, osfmk/mach/mach_voucherXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/vm_map_user.c, osfmk/mach/vm_map.h, osfmk/mach/vm_map_server.c, osfmk/mach/vm_map_server.h, osfmk/mach/vm_mapXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/resource_notify_user.c, osfmk/mach/resource_notify.h, osfmk/mach/resource_notify_server.c, osfmk/mach/resource_notify_server.h, osfmk/mach/resource_notifyXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/restartable_user.c, osfmk/mach/restartable.h, osfmk/mach/restartable_server.c, osfmk/mach/restartable_server.h, osfmk/mach/restartableXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/exc_user.c, osfmk/mach/exc.h, osfmk/mach/exc_server.c, osfmk/mach/exc_server.h, osfmk/mach/excXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/mach_exc_user.c, osfmk/mach/mach_exc.h, osfmk/mach/mach_exc_server.c, osfmk/mach/mach_exc_server.h, osfmk/mach/mach_excXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/notify_user.c, osfmk/mach/notify.h, osfmk/mach/notify_server.c, osfmk/mach/notify_server.h, osfmk/mach/notifyXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/task_user.c, osfmk/mach/task.h, osfmk/mach/task_server.c, osfmk/mach/task_server.h, osfmk/mach/taskXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/clock_user.c, osfmk/mach/clock.h, osfmk/mach/clock_server.c, osfmk/mach/clock_server.h, osfmk/mach/clockXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/clock_priv_user.c, osfmk/mach/clock_priv.h, osfmk/mach/clock_priv_server.c, osfmk/mach/clock_priv_server.h, osfmk/mach/clock_privXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/processor_user.c, osfmk/mach/processor.h, osfmk/mach/processor_server.c, osfmk/mach/processor_server.h, osfmk/mach/processorXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/host_priv_user.c, osfmk/mach/host_priv.h, osfmk/mach/host_priv_server.c, osfmk/mach/host_priv_server.h, osfmk/mach/host_privXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/host_security_user.c, osfmk/mach/host_security.h, osfmk/mach/host_security_server.c, osfmk/mach/host_security_server.h, osfmk/mach/host_securityXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/lock_set_user.c, osfmk/mach/lock_set.h, osfmk/mach/lock_set_server.c, osfmk/mach/lock_set_server.h, osfmk/mach/lock_setXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/mach_port_user.c, osfmk/mach/mach_port.h, osfmk/mach/mach_port_server.c, osfmk/mach/mach_port_server.h, osfmk/mach/mach_portXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/mach_vm_user.c, osfmk/mach/mach_vm.h, osfmk/mach/mach_vm_server.c, osfmk/mach/mach_vm_server.h, osfmk/mach/mach_vmXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/mach_host_user.c, osfmk/mach/mach_host.h, osfmk/mach/mach_host_server.c, osfmk/mach/mach_host_server.h, osfmk/mach/mach_hostXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/processor_set_user.c, osfmk/mach/processor_set.h, osfmk/mach/processor_set_server.c, osfmk/mach/processor_set_server.h, osfmk/mach/processor_setXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/thread_act_user.c, osfmk/mach/thread_act.h, osfmk/mach/thread_act_server.c, osfmk/mach/thread_act_server.h, osfmk/mach/thread_actXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/mach/clock_reply_user.c, osfmk/mach/clock_reply.h, osfmk/mach/clock_reply_server.c, osfmk/mach/clock_reply_server.h, osfmk/mach/clock_replyXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/device/device_user.c, osfmk/device/device.h, osfmk/device/device_server.c, osfmk/device/device_server.h, osfmk/device/deviceXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Generating osfmk/UserNotification/UNDReplyUser.c, osfmk/UserNotification/UNDReply.h, osfmk/UserNotification/UNDReplyServer.c, osfmk/UserNotification/UNDReplyServer.h, osfmk/UserNotification/UNDReplyXtraceMig.c
clang-12: warning: argument unused during compilation: '-arch i386' [-Wunused-command-line-argument]
Built target lkm_generate
Building the Linux kernel module
make[4]: Entering directory '/darling/src/external/lkm'
Running kernel version is 5.10.75-79.358.amzn2.x86_64
rm -f darling-mach.mod.o
make -C /lib/modules/5.10.75-79.358.amzn2.x86_64/build M=/darling/src/external/lkm modules
make[5]: Entering directory '/darling/src/external/lkm'
make[5]: *** /lib/modules/5.10.75-79.358.amzn2.x86_64/build: No such file or directory.  Stop.
make[5]: Leaving directory '/darling/src/external/lkm'
make[4]: *** [Makefile:615: default] Error 2
make[4]: Leaving directory '/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:71: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:58037: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:58044: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:20072: lkm] Error 2
```

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Clang | 12.0.1 |
| CMake | 3.21.3 |
| Linux Kernel | 5.10.75 |
| Darling | 97fc8eeaa |

**Comment by RealSerga** [comment] 2022-01-02 00:28
Kde neon(ubuntu) Exactly the same error



`KMS make.log for darling-mach-0.1 for kernel 5.11.0-41-generic (x86_64)
Sun 02 Jan 2022 05:24:22 AM +05
make: вход в каталог «/var/lib/dkms/darling-mach/0.1/build/lkm»
Running kernel version is 5.11.0-41-generic
rm -f darling-mach.mod.o
make -C /lib/modules/5.11.0-41-generic/build M=/var/lib/dkms/darling-mach/0.1/build/lkm modules
make[1]: вход в каталог «/usr/src/linux-headers-5.11.0-41-generic»
Running kernel version is 5.11.0-41-generic
Invoked by kernel build system, building for 5.11.0-41-generic
  CC [M]  /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.o
In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/port.h:90,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:74:
/var/lib/dkms/darling-mach/0.1/build/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
  137 | #define UINTPTR_MAX   UINT64_MAX
      |
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:6,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct.h:50,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:67:
./include/vdso/limits.h:17: note: this is the location of the previous definition
   17 | #define UINTPTR_MAX ULONG_MAX
      |
In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h:79,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/mach_types.h:115,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/clock.h:38,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/sched_prim.h:72,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:76:
/var/lib/dkms/darling-mach/0.1/build/lkm/libkern/os/overflow.h:66:3: error: #error os_overflow expects type-generic builtins
   66 | # error os_overflow expects type-generic builtins
      |   ^~~~~
In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/mach_types.h:115,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/clock.h:38,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/sched_prim.h:72,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:76:
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h: In function ‘mach_vm_round_page_overflow’:
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h:126:23: error: implicit declaration of function ‘os_add_overflow’; did you mean ‘os_add3_overflow’? [-Werror=implicit-fu>
  126 |          bool __ovr = os_add_overflow(in, (__typeof__(*out))PAGE_MASK, out); \
      |                       ^~~~~~~~~~~~~~~
/var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h:134:9: note: in expansion of macro ‘round_page_overflow’
  134 |  return round_page_overflow(in, out);
In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/bsd/sys/event.h:674,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_mqueue.h:82,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_port.h:91,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/task.h:126,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/thread.h:122,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/sched_prim.h:74,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:76:
/var/lib/dkms/darling-mach/0.1/build/lkm/bsd/sys/fcntl.h: At top level:
/var/lib/dkms/darling-mach/0.1/build/lkm/bsd/sys/fcntl.h:145: warning: "AT_EACCESS" redefined
  145 | #define AT_EACCESS              0x0010  /* Use effective ids in access check */
      |
In file included from ./include/linux/fcntl.h:6,
                 from ./include/linux/fs.h:26,
                 from ./include/linux/huge_mm.h:8,
                 from ./include/linux/mm.h:703,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct.h:55,
                 from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:67:
./include/uapi/linux/fcntl.h:99: note: this is the location of the previous definition
   99 | #define AT_EACCESS  0x200 /* Test access permitted for
      |
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.o] Ошибка 1
make[1]: *** [Makefile:1849: /var/lib/dkms/darling-mach/0.1/build/lkm] Ошибка 2
make[1]: выход из каталога «/usr/src/linux-headers-5.11.0-41-generic»
make: *** [Makefile:615: default] Ошибка 2
make: выход из каталога «/var/lib/dkms/darling-mach/0.1/build/lkm»
`

**Comment by acheong08** [comment] 2022-01-24 22:42
> Kde neon(ubuntu) Exactly the same error
> 
> ```
> KMS make.log for darling-mach-0.1 for kernel 5.11.0-41-generic (x86_64)
> Sun 02 Jan 2022 05:24:22 AM +05
> make: вход в каталог «/var/lib/dkms/darling-mach/0.1/build/lkm»
> Running kernel version is 5.11.0-41-generic
> rm -f darling-mach.mod.o
> make -C /lib/modules/5.11.0-41-generic/build M=/var/lib/dkms/darling-mach/0.1/build/lkm modules
> make[1]: вход в каталог «/usr/src/linux-headers-5.11.0-41-generic»
> Running kernel version is 5.11.0-41-generic
> Invoked by kernel build system, building for 5.11.0-41-generic
>   CC [M]  /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.o
> In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/port.h:90,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:74:
> /var/lib/dkms/darling-mach/0.1/build/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
>   137 | #define UINTPTR_MAX   UINT64_MAX
>       |
> In file included from ./include/linux/limits.h:7,
>                  from ./include/linux/kernel.h:6,
>                  from ./include/linux/list.h:9,
>                  from ./include/linux/module.h:12,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct.h:50,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:67:
> ./include/vdso/limits.h:17: note: this is the location of the previous definition
>    17 | #define UINTPTR_MAX ULONG_MAX
>       |
> In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h:79,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/mach_types.h:115,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/clock.h:38,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/sched_prim.h:72,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:76:
> /var/lib/dkms/darling-mach/0.1/build/lkm/libkern/os/overflow.h:66:3: error: #error os_overflow expects type-generic builtins
>    66 | # error os_overflow expects type-generic builtins
>       |   ^~~~~
> In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/mach_types.h:115,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/clock.h:38,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/sched_prim.h:72,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:76:
> /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h: In function ‘mach_vm_round_page_overflow’:
> /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h:126:23: error: implicit declaration of function ‘os_add_overflow’; did you mean ‘os_add3_overflow’? [-Werror=implicit-fu>
>   126 |          bool __ovr = os_add_overflow(in, (__typeof__(*out))PAGE_MASK, out); \
>       |                       ^~~~~~~~~~~~~~~
> /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/mach/vm_param.h:134:9: note: in expansion of macro ‘round_page_overflow’
>   134 |  return round_page_overflow(in, out);
> In file included from /var/lib/dkms/darling-mach/0.1/build/lkm/bsd/sys/event.h:674,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_mqueue.h:82,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_port.h:91,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/task.h:126,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/thread.h:122,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/kern/sched_prim.h:74,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:76:
> /var/lib/dkms/darling-mach/0.1/build/lkm/bsd/sys/fcntl.h: At top level:
> /var/lib/dkms/darling-mach/0.1/build/lkm/bsd/sys/fcntl.h:145: warning: "AT_EACCESS" redefined
>   145 | #define AT_EACCESS              0x0010  /* Use effective ids in access check */
>       |
> In file included from ./include/linux/fcntl.h:6,
>                  from ./include/linux/fs.h:26,
>                  from ./include/linux/huge_mm.h:8,
>                  from ./include/linux/mm.h:703,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/duct/duct.h:55,
>                  from /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.c:67:
> ./include/uapi/linux/fcntl.h:99: note: this is the location of the previous definition
>    99 | #define AT_EACCESS  0x200 /* Test access permitted for
>       |
> cc1: some warnings being treated as errors
> make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/darling-mach/0.1/build/lkm/osfmk/ipc/ipc_entry.o] Ошибка 1
> make[1]: *** [Makefile:1849: /var/lib/dkms/darling-mach/0.1/build/lkm] Ошибка 2
> make[1]: выход из каталога «/usr/src/linux-headers-5.11.0-41-generic»
> make: *** [Makefile:615: default] Ошибка 2
> make: выход из каталога «/var/lib/dkms/darling-mach/0.1/build/lkm»
> ```

Same error as @RealSerga on Ubuntu with kernel 5.16.2-t2

**Comment by facekapow** [comment] 2022-01-25 13:16
What version of GCC are you using? (what does `gcc --version` say)

**Comment by acheong08** [comment] 2022-01-26 00:04
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by acheong08** [comment] 2022-01-26 00:11
Same error occurs with `gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0` but no longer treats the warning as an error.

**Comment by acheong08** [comment] 2022-01-26 00:24
Built and installed after setting gcc 10 as default.

**Comment by acheong08** [comment] 2022-01-26 00:25
> What version of GCC are you using? (what does `gcc --version` say)

Thanks for the tip

**Comment by facekapow** [comment] 2022-01-29 23:06
Duplicate of #1012

**Closed by facekapow** 2022-01-29 23:06 UTC
Labels: Awaiting Response
