### ISSUE TITLE
Ubuntu 21.04 building issue .deb install failed

### ISSUE THREAD

**Issue by Manasx100** [darlinghq/darling#957] opened 2021-04-29 11:57 UTC
Darling mach not builds normally also .deb instal failed LOG bellow
[LOG.zip](https://github.com/darlinghq/darling/files/6398316/LOG.zip)

**Comment by JCWasmx86** [comment] 2021-04-30 05:15
The same error was here: https://github.com/darlinghq/darling/issues/933

**Comment by Manasx100** [comment] 2021-04-30 15:32
Probably it is a issue with the kernel.

**Comment by facekapow** [comment] 2021-05-22 19:47
Closing as a duplicate of #933

**Closed by facekapow** 2021-05-22 19:47 UTC
Labels: Duplicate
