### ISSUE TITLE
OpenSSL 0.9 doesn't support TLS v1.1 & v1.2

### ISSUE THREAD

**Issue by bugaevc** [darlinghq/darling#245] opened 2017-01-17 12:03 UTC
To reproduce:
```
Darling [~]$ curl https://rustup.rs
curl: (35) Unknown SSL protocol error in connection to rustup.rs:443
````

Relevant `strace` output:
```
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 4
setsockopt(4, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPINTVL, [60], 4) = 0
setsockopt(4, SOL_TCP, TCP_KEEPIDLE, [60], 4) = 0
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
gettimeofday({1484654285, 469266}, NULL) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("54.215.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)
gettimeofday({1484654285, 470452}, NULL) = 0
gettimeofday({1484654285, 470837}, NULL) = 0
gettimeofday({1484654285, 470869}, NULL) = 0
poll([{fd=4, events=POLLOUT}], 1, 0)    = 0 (Timeout)
gettimeofday({1484654285, 471139}, NULL) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
gettimeofday({1484654285, 471204}, NULL) = 0
gettimeofday({1484654285, 471228}, NULL) = 0
gettimeofday({1484654285, 471258}, NULL) = 0
poll([{fd=4, events=POLLOUT}], 1, 197)  = 0 (Timeout)
gettimeofday({1484654285, 670262}, NULL) = 0
gettimeofday({1484654285, 670294}, NULL) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
gettimeofday({1484654285, 670633}, NULL) = 0
poll([{fd=4, events=POLLOUT}], 1, 0)    = 0 (Timeout)
gettimeofday({1484654285, 670686}, NULL) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
gettimeofday({1484654285, 670733}, NULL) = 0
gettimeofday({1484654285, 670755}, NULL) = 0
poll([{fd=4, events=POLLOUT}], 1, 1000) = 1 ([{fd=4, revents=POLLOUT}])
gettimeofday({1484654285, 671491}, NULL) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
gettimeofday({1484654285, 671582}, NULL) = 0
poll([{fd=4, events=POLLOUT}], 1, 0)    = 1 ([{fd=4, revents=POLLOUT}])
getsockopt(4, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
gettimeofday({1484654285, 671771}, NULL) = 0
getpeername(4, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("54.215.0.2")}, [16]) = 0
getsockname(4, {sa_family=AF_INET, sin_port=htons(36080), sin_addr=inet_addr("10.0.2.15")}, [16]) = 0
gettimeofday({1484654285, 672058}, NULL) = 0
gettimeofday({1484654285, 672096}, NULL) = 0
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 5
fstat(5, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
select(6, [5], NULL, NULL, {0, 10000})  = 1 (in [5], left {0, 9999})
read(5, "\257\333qz\334\212\2305\232Ai\332\"\234\231\32\227\357\265\326\2100\252\351o\311_\32\273\231uJ", 32) = 32
close(5)                                = 0
getuid()                                = 1000
gettimeofday({1484654285, 673058}, NULL) = 0
getuid()                                = 1000
geteuid()                               = 1000
getgid()                                = 1000
getegid()                               = 1000
getuid()                                = 1000
geteuid()                               = 1000
getgid()                                = 1000
getegid()                               = 1000
stat("/Users/sergey/.rnd", 0x7ffe9664f4e0) = -1 ENOENT (No such file or directory)
gettimeofday({1484654285, 674340}, NULL) = 0
gettimeofday({1484654285, 674620}, NULL) = 0
gettimeofday({1484654285, 674956}, NULL) = 0
write(4, "\26\3\1\0Y\1\0\0U\3\1X~\6\315\353\361{E\253\335\32493cC\375\177\314\3234\21"..., 94) = 94
read(4, 0x7f785206f400, 7)              = -1 EAGAIN (Resource temporarily unavailable)
gettimeofday({1484654285, 675555}, NULL) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
gettimeofday({1484654285, 675684}, NULL) = 0
gettimeofday({1484654285, 675710}, NULL) = 0
poll([{fd=4, events=POLLIN}], 1, 1000)  = 1 ([{fd=4, revents=POLLIN|POLLERR|POLLHUP}])
gettimeofday({1484654285, 878937}, NULL) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
gettimeofday({1484654285, 879421}, NULL) = 0
poll([{fd=4, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=4, revents=POLLIN|POLLRDNORM|POLLERR|POLLHUP}])
gettimeofday({1484654285, 879687}, NULL) = 0
read(4, 0x7f785206f400, 7)              = -1 ECONNRESET (Connection reset by peer)
rt_sigaction(SIGPIPE, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, {SIG_IGN, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f7853594304}, 8) = 0
gettimeofday({1484654285, 880503}, NULL) = 0
close(4)
```

Meaning that the protocol error happens before it even starts to look up certificates.

Unlike #161, https://rustup.rs, especially https://sh.rustup.rs, is definitely curl'able from macOS.

**Comment by bugaevc** [comment] 2017-01-17 12:22
This is because https://rustup.rs supports TLSvs1.1 & TLSv1.2, the versions that OpenSSL 0.9 doesn't support.

macOS uses coreTLS, which requires CoreCrypto.

**Comment by ahyattdev** [comment] 2018-05-01 19:25
We have CoreTLS now, we just need CoreCrypto to be implemented. Closing as a duplicate of #380.

**Closed by ahyattdev** 2018-05-01 19:25 UTC
Labels: enhancement
