### ISSUE TITLE
Cannot compile LKM

### ISSUE THREAD

**Issue by alexey-milovidov** [darlinghq/darling#1099] opened 2022-01-29 20:05 UTC
**Build Log**

```
Scanning dependencies of target lkm
Building the Linux kernel module
make[4]: Entering directory '/home/ubuntu/darling/src/external/lkm'
Running kernel version is 5.11.0-1022-aws
rm -f darling-mach.mod.o
make -C /lib/modules/5.11.0-1022-aws/build M=/home/ubuntu/darling/src/external/lkm modules
make[5]: Entering directory '/usr/src/linux-headers-5.11.0-1022-aws'
Running kernel version is 5.11.0-1022-aws
Invoked by kernel build system, building for 5.11.0-1022-aws
  CC [M]  /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.o
In file included from /home/ubuntu/darling/src/external/lkm/osfmk/mach/port.h:90,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.c:74:
/home/ubuntu/darling/src/external/lkm/EXTERNAL_HEADERS/stdint.h:137: warning: "UINTPTR_MAX" redefined
  137 | #define UINTPTR_MAX   UINT64_MAX
      | 
In file included from ./include/linux/limits.h:7,
                 from ./include/linux/kernel.h:6,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:12,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/duct/duct.h:50,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.c:67:
./include/vdso/limits.h:17: note: this is the location of the previous definition
   17 | #define UINTPTR_MAX ULONG_MAX
      | 
In file included from /home/ubuntu/darling/src/external/lkm/osfmk/mach/vm_param.h:79,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/mach/mach_types.h:115,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/kern/clock.h:38,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/kern/sched_prim.h:72,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.c:76:
/home/ubuntu/darling/src/external/lkm/libkern/os/overflow.h:66:3: error: #error os_overflow expects type-generic builtins
   66 | # error os_overflow expects type-generic builtins
      |   ^~~~~
In file included from /home/ubuntu/darling/src/external/lkm/osfmk/mach/mach_types.h:115,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/kern/clock.h:38,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/kern/sched_prim.h:72,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.c:76:
/home/ubuntu/darling/src/external/lkm/osfmk/mach/vm_param.h: In function ‘mach_vm_round_page_overflow’:
/home/ubuntu/darling/src/external/lkm/osfmk/mach/vm_param.h:126:23: error: implicit declaration of function ‘os_add_overflow’; did you mean ‘os_add3_overflow’? [-Werror=implicit-function-declaration]
  126 |          bool __ovr = os_add_overflow(in, (__typeof__(*out))PAGE_MASK, out); \
      |                       ^~~~~~~~~~~~~~~
/home/ubuntu/darling/src/external/lkm/osfmk/mach/vm_param.h:134:9: note: in expansion of macro ‘round_page_overflow’
  134 |  return round_page_overflow(in, out);
      |         ^~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/darling/src/external/lkm/bsd/sys/event.h:674,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_mqueue.h:82,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_port.h:91,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/kern/task.h:126,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/kern/thread.h:122,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/kern/sched_prim.h:74,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.c:76:
/home/ubuntu/darling/src/external/lkm/bsd/sys/fcntl.h: At top level:
/home/ubuntu/darling/src/external/lkm/bsd/sys/fcntl.h:145: warning: "AT_EACCESS" redefined
  145 | #define AT_EACCESS              0x0010  /* Use effective ids in access check */
      | 
In file included from ./include/linux/fcntl.h:6,
                 from ./include/linux/fs.h:26,
                 from ./include/linux/huge_mm.h:8,
                 from ./include/linux/mm.h:703,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/duct/duct.h:55,
                 from /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.c:67:
./include/uapi/linux/fcntl.h:99: note: this is the location of the previous definition
   99 | #define AT_EACCESS  0x200 /* Test access permitted for
      | 
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:288: /home/ubuntu/darling/src/external/lkm/osfmk/ipc/ipc_entry.o] Error 1
make[5]: *** [Makefile:1849: /home/ubuntu/darling/src/external/lkm] Error 2
make[5]: Leaving directory '/usr/src/linux-headers-5.11.0-1022-aws'
make[4]: *** [Makefile:618: default] Error 2
make[4]: Leaving directory '/home/ubuntu/darling/src/external/lkm'
make[3]: *** [src/external/lkm/CMakeFiles/lkm.dir/build.make:58: src/external/lkm/CMakeFiles/lkm] Error 2
make[2]: *** [CMakeFiles/Makefile2:61672: src/external/lkm/CMakeFiles/lkm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:61679: src/external/lkm/CMakeFiles/lkm.dir/rule] Error 2
make: *** [Makefile:20158: lkm] Error 2
```

**System Information**
What system are you building with?

```
ubuntu@ip-172-31-27-112:~/darling/build$ uname -a
Linux ip-172-31-27-112 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ip-172-31-27-112:~/darling/build$ clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

ubuntu@ip-172-31-27-112:~/darling/build$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

ubuntu@ip-172-31-27-112:~/darling/build$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

ubuntu@ip-172-31-27-112:~/darling/build$ git log | head -n10
commit 597325bc702e7b0893ade8272000a4086b23f121
Merge: df8cbdfc9 4095b6247
Author: Ariel Abreu <facekapow@outlook.com>
Date:   Tue Jan 25 10:00:28 2022 -0500

    Merge pull request #1028 from JCWasmx86/master
    
    Added CloudKit stubs
```

**Comment by facekapow** [comment] 2022-01-29 20:45
Try the `gcc-has-builtin-fix` LKM branch: go to the LKM source directory and do `git checkout gcc-has-builtin-fix`, then try rebuilding.

**Comment by facekapow** [comment] 2022-01-29 23:07
Duplicate of #1012

**Closed by facekapow** 2022-01-29 23:07 UTC
