### ISSUE TITLE
FileTypeResolver.cpp.o

### ISSUE THREAD

**Issue by HidePerson** [darlinghq/darling#393] opened 2018-06-05 12:49 UTC
`Building CXX object src/external/xcbuild/Libraries/pbxbuild/CMakeFiles/pbxbuild.dir/Sources/FileTypeResolver.cpp.o`
`.../darling/src/external/xcbuild/Libraries/pbxbuild/Sources/FileTypeResolver.cpp:34:70: error:`

default initialization of an object of const type 'const std::unordered_set<pbxspec::PBX::FileType::shared_ptr>' (aka 'const
      unordered_set<shared_ptr<pbxspec::PBX::FileType> >') without a
      user-provided default constructor

`const std::unordered_set<pbxspec::PBX::FileType::shared_ptr> emptySet;`

All libraries from instructions are installed.
What can I do for solving this problem?
OS: Linux Debian 9.4 Stretch

**Comment by LubosD** [comment] 2018-06-05 12:50
Duplicate of #389

**Closed by LubosD** 2018-06-05 12:50 UTC
