### ISSUE TITLE
openSUSE build failed due to invalid link arch

### ISSUE THREAD

**Issue by aviumcaravan** [darlinghq/darling#889] opened 2020-10-26 13:15 UTC
hey, so i decided to attempt and build Darling on openSUSE. i resolved the dependencies, and yet i am greeted with **this**:
```
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../librt.so when searching for -lrt
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../libc.so when searching for -lc
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../Scrt1.o' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../crti.o' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../crtn.o' is incompatible with i386 output
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../Scrt1.o: file class ELFCLASS64 incompatible with ELFCLASS32
```

how could i potentially fix this? or perhaps could i recieve a prebuild RPM for Tumbleweed x86_64? thanks in advance

**Comment by HinTak** [comment] 2020-10-26 13:23
I think you are missing 32-bit support libraries on your suse box. Darling can run both 32-bit and 64-bit apple binaries so needs both set of linux libraries to build.

**Comment by wiktornowicki** [comment] 2020-10-26 14:42
> I think you are missing 32-bit support libraries on your suse box. Darling can run both 32-bit and 64-bit apple binaries so needs both set of linux libraries to build.

i have an uncountable amount of 32-bit compatibility libraries, all of them are the dependencies. i might just jump to a different distro, but i was wondering whether a trick like this was possible.

**Comment by HinTak** [comment] 2020-10-26 15:50
See if you can find anything that looks like `...i686-suse-linux/10/../../../crtn.o` etc on your suse system. If you can't, find out how to get them.

**Comment by expeehaa** [comment] 2021-02-01 22:17
I’m facing the same issue and tracked it down a bit further. I don’t know if that helps or how other distros handle it, but here is what I found. (short disclaimer: I have never worked with clang before and don’t really know how it works)

`make` fails in `src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/build.make:118`, which calls cmake with `src/libelfloader/native/CMakeFiles/elfloader_dummy32.dir/link.txt` as an argument. Manually running the command in there reproduces the error.

By appending `-L/usr/lib` to the command, one can get rid of the first 4 errors.
```
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../librt.so when searching for -lrt
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../libc.so when searching for -lc
```

For `/usr/bin/../lib64/gcc/x86_64-suse-linux/10/../../../Scrt1.o` and the other 2 files, those can also be found in `/usr/lib/` (which I suppose should work?). However, those are not being used and I don’t know why.

I hope this helps to find a solution, I’ld really like to try Darling. I’m available for further questions, if necessary (also on the discord server).

**Comment by wiktornowicki** [comment] 2021-02-10 15:19
thank you all ever so much, i'll try to try your solutions when i have a chance!

**Comment by facekapow** [comment] 2023-10-16 02:03
Closing this since the issue is old but also our OpenSUSE build instructions now include a note saying you have to disable the 32-bit components.

**Closed by facekapow** 2023-10-16 02:03 UTC
Labels: Awaiting Response
