### ISSUE TITLE
error: 'TARGET_OS_DRIVERKIT' ? "Make error 10%

### ISSUE THREAD

**Issue by kinggx9** [darlinghq/darling#892] opened 2020-11-17 12:54 UTC
**Build Log**
I am building the latest version
```
[ 10%] Building CXX object src/dyld/CMakeFiles/system_dyld_obj.dir/src/dyldAPIsInLibSystem.o
clang-11: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
clang-11: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
/home/xxxx/Desktop/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:34:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT
     ^
In file included from /home/xxxxx/Desktop/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:50:
/home/xxxx/Desktop/darling/src/dyld/src/ImageLoader.h:46:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
In file included from /home/xxxx/Desktop/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:50:
In file included from /home/xxxx/Desktop/darling/src/dyld/src/ImageLoader.h:53:
In file included from /home/xxxx/Desktop/darling/src/dyld/dyld3/shared-cache/DyldSharedCache.h:41:
In file included from /home/xxxx/Desktop/darling/src/dyld/dyld3/MachOAnalyzer.h:28:
In file included from /home/xxxx/Desktop/darling/src/dyld/dyld3/MachOLoaded.h:29:
/home/xxxx/Desktop/darling/src/dyld/dyld3/Array.h:33:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
/home/xxxx/Desktop/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:85:41: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if __IPHONE_OS_VERSION_MIN_REQUIRED || TARGET_OS_DRIVERKIT
                                        ^
/home/xxxx/Desktop/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:1381:5: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_DRIVERKIT
    ^
/home/xxxx/Desktop/darling/src/dyld/src/dyldAPIsInLibSystem.cpp:1488:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT
     ^
6 errors generated.
make[2]: *** [src/dyld/CMakeFiles/system_dyld_obj.dir/build.make:82: src/dyld/CMakeFiles/system_dyld_obj.dir/src/dyldAPIsInLibSystem.o] error 1
make[1]: *** [CMakeFiles/Makefile2:16608: src/dyld/CMakeFiles/system_dyld_obj.dir/all] error 2
make: *** [Makefile:149: all] error 2
```

**System Information**
Arch linux 
| Software | Version |
| --- | --- |
| Clang | 11 |
| CMake | 3.18.4|
| Linux Kernel | 5.4.77 |
Thanks!

**Comment by teras** [comment] 2020-11-18 08:10
I have the same problem with Ubuntu 20.10

**Comment by n0u53** [comment] 2020-11-21 15:19
Same here on Archlinux
Exact same output like the first post.
@kinggx9 can you pleas try to rename your or add the "error: 'TARGET_OS_DRIVERKIT' ? "Make error 10%" tells nothing and search engine looking for thread title first

**Comment by rdrpenguin04** [comment] 2020-11-26 17:31
Duplicate of #856

**Comment by facekapow** [comment] 2020-11-27 03:02
Closing in favor of #856

**Closed by facekapow** 2020-11-27 03:02 UTC
